### ISSUE TITLE
[BUG]: CEF 3809 使用 QCefview 编译后，加载 220M 的 pdf 会报错

### ISSUE THREAD

**Issue by ZhenZY** [CefView/QCefView#117]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
...

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. 编译 3809 版本的CEF，本地开启一个 http 服务，加载该服务下的一个 pdf
2. 这个pdf是按需加载的，也就是说，只加载页面可视区域的内容（这个是开源插件pdf.js的配置）
3. 加载pdf报错
![image](https://user-images.githubusercontent.com/25266953/174542566-9029a361-1763-4adf-a48f-7a5e048a1181.png)
据猜测是限制了CEF的内存，导致了超过内存时加载异常（小的PDF可以正常渲染）

**Expected behavior 【正确的预期行为】**
使用下载的 CEF 官方 demo cefsimple 编译，显示正常，500M也正常

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
...

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息)
[//]: # (Please complete the following information)
 - OS & Version: [e.g. Windows/macOS/Linux]
 - Qt Version: 5.6.3
 - CEF Version: 3809
 - OSR/NCW Mode:
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by ZhenZY** [comment]
您好，我是姜丽珍，您的邮件我已收到，我将尽快回复您，谢谢。

**Comment by ZhenZY** [comment]
我跑的是2020/8/29提交的版本，没有命令

**Comment by ZhenZY** [comment]
你好，是否还有其他思路可以解决这个问题。

**Comment by ZhenZY** [comment]
您好，我是姜丽珍，您的邮件我已收到，我将尽快回复您，谢谢。

**Comment by ZhenZY** [comment]
好兄弟,已经解决了,QCefView 默认属性是没有打开大地址编译.CefSimple 有.QCefWing 开启大地址编译即可.感谢支持

**Comment by tishion** [comment]
辛苦定位问题，我记一下，后续在demo中增加编译选项支持。
msbuild /largeaddressaware
gcc --large-address-aware
