### ISSUE TITLE
[BUG]: linux下右键菜单功能如何实现？

### ISSUE THREAD

**Issue by tonyzhou1985** [CefView/QCefView#119]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
1.0.3版本在linux下只有osr模式，在osr模式下，右键菜单不能显示。

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
希望能正常显示右键菜单功能

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息)
[//]: # (Please complete the following information)
 - OS & Version: Linux
 - Qt Version:qt5.12.10
 - CEF Version:95.7.18
 - OSR/NCW Mode:OSR
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by tonyzhou1985** [comment]
用qt自己绘制是可以实现自定义的菜单，如果要实现原有的那些右键菜单，比如输入框右键【复制】【粘帖】【全选】等功能如何实现？另外qt实现的菜单显示位置如何定位？

**Comment by tishion** [comment]
CefFrame有一些方法，不过目前没有通过QCefView暴露出来。
https://magpcss.org/ceforum/apidocs3/projects/(default)/CefFrame.html

```cpp
  // Execute undo in this frame.
  ///
  /*--cef()--*/
  virtual void Undo() = 0;

  ///
  // Execute redo in this frame.
  ///
  /*--cef()--*/
  virtual void Redo() = 0;

  ///
  // Execute cut in this frame.
  ///
  /*--cef()--*/
  virtual void Cut() = 0;

  ///
  // Execute copy in this frame.
  ///
  /*--cef()--*/
  virtual void Copy() = 0;

  ///
  // Execute paste in this frame.
  ///
  /*--cef()--*/
  virtual void Paste() = 0;

  ///
  // Execute delete in this frame.
  ///
  /*--cef(capi_name=del)--*/
  virtual void Delete() = 0;

  ///
  // Execute select all in this frame.
  ///
  /*--cef()--*/
  virtual void SelectAll() = 0;
```

后面再增加方法暴露这几个方法的功能。

**Comment by tonyzhou1985** [comment]
非常感谢大佬解答。

**Comment by tishion** [comment]
https://github.com/CefView/QCefView/pull/124
OSR增加了右键菜单的处理，右键菜单的行为现在受到setContextMenuPolicy函数的控制。
如果当前QCefView设置了Qt::DefaultContextMenuPolicy，则显示CEF默认的native 右键菜单，其他任何值，都不会显示默认菜单，可以考虑使用Qt绘制，或者JavaScript绘制。
