### ISSUE TITLE
是否支持mingw编译呢？

### ISSUE THREAD

**Issue by dearbub** [CefView/QCefView#122]
编译时出现此问题：
![图片](https://user-images.githubusercontent.com/9819222/175877290-d5433a91-9a7f-41c0-9996-ed3b431f6a74.png)

编译输出：
14:44:16: 为项目QCefView执行步骤 ...
14:44:16: 正在启动 "D:\Qt\Qt6.2.2\Tools\CMake_64\bin\cmake.exe" --build E:/source/build-QCefView-main-Desktop_Qt_6_2_2_MinGW_64_bit-Debug --target all

[1/232 10.0/sec] Building CXX object CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/transfer_util.cc.obj
FAILED: CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/transfer_util.cc.obj 
D:\Qt\Qt6.2.2\Tools\mingw1120_64\bin\g++.exe -DNOMINMAX -DOS_WINDOWS=1 -DUNICODE -DWIN32 -DWIN32_LEAN_AND_MEAN -DWINVER=0x0601 -DWRAPPING_CEF_SHARED -D_HAS_EXCEPTIONS=0 -D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING=1 -D_UNICODE -D_WIN32 -D_WIN32_WINNT=0x601 -D_WINDOWS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -IE:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64 /MDd /MP /Gy /GR- /W4 /WX /wd4100 /wd4127 /wd4244 /wd4324 /wd4481 /wd4512 /wd4701 /wd4702 /wd4996 /Zi /RTC1 /Od -std=gnu++14 -MD -MT CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/transfer_util.cc.obj -MF CefViewCore\libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\transfer_util.cc.obj.d -o CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/transfer_util.cc.obj -c E:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64/libcef_dll/transfer_util.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[2/232 19.7/sec] Building CXX object CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_atomic_flag.cc.obj
FAILED: CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_atomic_flag.cc.obj 
D:\Qt\Qt6.2.2\Tools\mingw1120_64\bin\g++.exe -DNOMINMAX -DOS_WINDOWS=1 -DUNICODE -DWIN32 -DWIN32_LEAN_AND_MEAN -DWINVER=0x0601 -DWRAPPING_CEF_SHARED -D_HAS_EXCEPTIONS=0 -D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING=1 -D_UNICODE -D_WIN32 -D_WIN32_WINNT=0x601 -D_WINDOWS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -IE:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64 /MDd /MP /Gy /GR- /W4 /WX /wd4100 /wd4127 /wd4244 /wd4324 /wd4481 /wd4512 /wd4701 /wd4702 /wd4996 /Zi /RTC1 /Od -std=gnu++14 -MD -MT CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_atomic_flag.cc.obj -MF CefViewCore\libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\base\cef_atomic_flag.cc.obj.d -o CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_atomic_flag.cc.obj -c E:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64/libcef_dll/base/cef_atomic_flag.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[3/232 29.2/sec] Building CXX object CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_helpers.cc.obj
FAILED: CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_helpers.cc.obj 
D:\Qt\Qt6.2.2\Tools\mingw1120_64\bin\g++.exe -DNOMINMAX -DOS_WINDOWS=1 -DUNICODE -DWIN32 -DWIN32_LEAN_AND_MEAN -DWINVER=0x0601 -DWRAPPING_CEF_SHARED -D_HAS_EXCEPTIONS=0 -D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING=1 -D_UNICODE -D_WIN32 -D_WIN32_WINNT=0x601 -D_WINDOWS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -IE:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64 /MDd /MP /Gy /GR- /W4 /WX /wd4100 /wd4127 /wd4244 /wd4324 /wd4481 /wd4512 /wd4701 /wd4702 /wd4996 /Zi /RTC1 /Od -std=gnu++14 -MD -MT CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_helpers.cc.obj -MF CefViewCore\libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\base\cef_callback_helpers.cc.obj.d -o CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_helpers.cc.obj -c E:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64/libcef_dll/base/cef_callback_helpers.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[4/232 38.4/sec] Building CXX object CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/shutdown_checker.cc.obj
FAILED: CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/shutdown_checker.cc.obj 
D:\Qt\Qt6.2.2\Tools\mingw1120_64\bin\g++.exe -DNOMINMAX -DOS_WINDOWS=1 -DUNICODE -DWIN32 -DWIN32_LEAN_AND_MEAN -DWINVER=0x0601 -DWRAPPING_CEF_SHARED -D_HAS_EXCEPTIONS=0 -D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING=1 -D_UNICODE -D_WIN32 -D_WIN32_WINNT=0x601 -D_WINDOWS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -IE:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64 /MDd /MP /Gy /GR- /W4 /WX /wd4100 /wd4127 /wd4244 /wd4324 /wd4481 /wd4512 /wd4701 /wd4702 /wd4996 /Zi /RTC1 /Od -std=gnu++14 -MD -MT CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/shutdown_checker.cc.obj -MF CefViewCore\libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\shutdown_checker.cc.obj.d -o CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/shutdown_checker.cc.obj -c E:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64/libcef_dll/shutdown_checker.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[5/232 47.9/sec] Building CXX object CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.obj
FAILED: CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.obj 
D:\Qt\Qt6.2.2\Tools\mingw1120_64\bin\g++.exe -DNOMINMAX -DOS_WINDOWS=1 -DUNICODE -DWIN32 -DWIN32_LEAN_AND_MEAN -DWINVER=0x0601 -DWRAPPING_CEF_SHARED -D_HAS_EXCEPTIONS=0 -D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING=1 -D_UNICODE -D_WIN32 -D_WIN32_WINNT=0x601 -D_WINDOWS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -IE:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64 /MDd /MP /Gy /GR- /W4 /WX /wd4100 /wd4127 /wd4244 /wd4324 /wd4481 /wd4512 /wd4701 /wd4702 /wd4996 /Zi /RTC1 /Od -std=gnu++14 -MD -MT CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.obj -MF CefViewCore\libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\base\cef_lock.cc.obj.d -o CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.obj -c E:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64/libcef_dll/base/cef_lock.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[6/232 57.2/sec] Building CXX object CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.obj
FAILED: CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.obj 
D:\Qt\Qt6.2.2\Tools\mingw1120_64\bin\g++.exe -DNOMINMAX -DOS_WINDOWS=1 -DUNICODE -DWIN32 -DWIN32_LEAN_AND_MEAN -DWINVER=0x0601 -DWRAPPING_CEF_SHARED -D_HAS_EXCEPTIONS=0 -D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING=1 -D_UNICODE -D_WIN32 -D_WIN32_WINNT=0x601 -D_WINDOWS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -IE:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64 /MDd /MP /Gy /GR- /W4 /WX /wd4100 /wd4127 /wd4244 /wd4324 /wd4481 /wd4512 /wd4701 /wd4702 /wd4996 /Zi /RTC1 /Od -std=gnu++14 -MD -MT CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.obj -MF CefViewCore\libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\base\cef_callback_internal.cc.obj.d -o CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.obj -c E:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64/libcef_dll/base/cef_callback_internal.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[7/232 66.5/sec] Building CXX object CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_logging.cc.obj
FAILED: CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_logging.cc.obj 
D:\Qt\Qt6.2.2\Tools\mingw1120_64\bin\g++.exe -DNOMINMAX -DOS_WINDOWS=1 -DUNICODE -DWIN32 -DWIN32_LEAN_AND_MEAN -DWINVER=0x0601 -DWRAPPING_CEF_SHARED -D_HAS_EXCEPTIONS=0 -D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING=1 -D_UNICODE -D_WIN32 -D_WIN32_WINNT=0x601 -D_WINDOWS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -IE:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64 /MDd /MP /Gy /GR- /W4 /WX /wd4100 /wd4127 /wd4244 /wd4324 /wd4481 /wd4512 /wd4701 /wd4702 /wd4996 /Zi /RTC1 /Od -std=gnu++14 -MD -MT CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_logging.cc.obj -MF CefViewCore\libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\base\cef_logging.cc.obj.d -o CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_logging.cc.obj -c E:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64/libcef_dll/base/cef_logging.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[8/232 75.5/sec] Building CXX object CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock_impl.cc.obj
FAILED: CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock_impl.cc.obj 
D:\Qt\Qt6.2.2\Tools\mingw1120_64\bin\g++.exe -DNOMINMAX -DOS_WINDOWS=1 -DUNICODE -DWIN32 -DWIN32_LEAN_AND_MEAN -DWINVER=0x0601 -DWRAPPING_CEF_SHARED -D_HAS_EXCEPTIONS=0 -D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING=1 -D_UNICODE -D_WIN32 -D_WIN32_WINNT=0x601 -D_WINDOWS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -IE:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64 /MDd /MP /Gy /GR- /W4 /WX /wd4100 /wd4127 /wd4244 /wd4324 /wd4481 /wd4512 /wd4701 /wd4702 /wd4996 /Zi /RTC1 /Od -std=gnu++14 -MD -MT CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock_impl.cc.obj -MF CefViewCore\libcef_dll_wrapper\CMakeFiles\libcef_dll_wrapper.dir\base\cef_lock_impl.cc.obj.d -o CefViewCore/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock_impl.cc.obj -c E:/source/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64/libcef_dll/base/cef_lock_impl.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
ninja: build stopped: subcommand failed.
14:44:16: 进程"D:\Qt\Qt6.2.2\Tools\CMake_64\bin\cmake.exe"退出，退出代码 1 。
Error while building/deploying project QCefView (kit: Desktop Qt 6.2.2 MinGW 64-bit)
When executing step "Build"
14:44:16: Elapsed time: 00:00.

**Comment by tishion** [comment]
Qt支持，但是CEF是不是官方支持我不确定，你自己可以尝试修改一下。

**Comment by dearbub** [comment]
已收到！

**Comment by superpig** [comment]
> 已收到！

同样的诉求，你解决了 cef mingw 编译吗？

**Comment by xiaobingcaicai** [comment]
> 已收到！

同样的诉求，是否解决了mingw的编译？

**Comment by xiaobingcaicai** [comment]
> Qt支持，但是CEF是不是官方支持我不确定，你自己可以尝试修改一下。

我修改了官方的cef包，可以mingw编译生成libcef_dll_wrapper.a静态库，但是编译CefViewCore时需要libcef的lib库，还需要修改CefViewCore的文件
