### ISSUE TITLE
[BUG]: 页面无法下载文件

### ISSUE THREAD

**Issue by tonyzhou1985** [CefView/QCefView#125]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
没有下载功能。CefDownloadHandler接口没有引出来。

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
期望和普通浏览器一样有下载功能

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息)
[//]: # (Please complete the following information)
 - OS & Version: Ubuntu 18.04
 - Qt Version: Qt5.12.10
 - CEF Version: 95
 - OSR/NCW Mode: OSR
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by tishion** [comment]
QCefView没有支持这个功能的计划，如果需要请自行添加。
