### ISSUE TITLE
[BUG]:macOS 编译最新版本的QCefViewTest 报错“framework not found QcefView"

### ISSUE THREAD

**Issue by ZhenZY** [CefView/QCefView#126]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
...
<img width="1440" alt="截屏2022-07-13 下午7 11 50" src="https://user-images.githubusercontent.com/25266953/178720644-91557780-cab8-411a-8c09-f5a0b0042041.png">

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. 按照文档步骤“https://cefview.github.io/QCefView/zh/docs/intros/buiding” 在 “./build/macos.x86_64" 下生成 xcode 项目
2. 用xcode 打开 QCefViewTest.xcodeproj,编译报错如上图

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
...
build success
**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息)
[//]: # (Please complete the following information)
 - OS & Version: macOS 11.3.1
 - Qt Version: 5.6.3
 - CEF Version: cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_macosx64
 - xcode Version: 13.2.1
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by tishion** [comment]
https://github.com/CefView/QCefView/actions/workflows/build-macos-x86_64.yml

你用的5.6版本的Qt，有问题的话请你自己解决一下吧。

**Comment by ZhenZY** [comment]
那你用的是哪个版本,文档里写的是兼容QT5.x和6.x

**Comment by tishion** [comment]
这是你自己编译环境的问题，你找不到QCefView framework 要么是你QCefView没有编译成功，要么是你没有把framework拷贝到指定的目录，这些工作都是cmake里写好的自动化脚本完成的。

自己花点时间理解一下项目。

**Comment by ZhenZY** [comment]
对了,还是想问一下,你当时用的mac 版的QT版本号是多少.因为我换了个版本就没有这个问题了.但是有新问题,看上去不是环境多问题

duplicate symbol '_main' in:
    /Users/listen/code/frontend/qt/QCefView/build/example/QCefViewTest/QCefViewTest.build/Debug/QCefViewTest.build/Objects-normal/x86_64/CMakeCXXCompilerId.o
    /Users/listen/code/frontend/qt/QCefView/build/example/QCefViewTest/QCefViewTest.build/Debug/QCefViewTest.build/Objects-normal/x86_64/main.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tishion** [comment]
开发过程中使用的Qt是5.12和6.xx的

**Comment by ZhenZY** [comment]
好的,感谢,我用 5.12.2 ,修改了一两句代码,关掉离屏渲染就正常了
