### ISSUE TITLE
[BUG]: osr 和 ncw 模式下界面布局异常

### ISSUE THREAD

**Issue by xiaoniao88** [CefView/QCefView#127]
您好，我这边工程编译后，浏览网页出现了界面布局异常，不知道是什么原因，向您咨询一下

**Describe the bug 【Bug描述】** 
osr 和 ncw 模式下界面布局异常

浏览的界面布局异常
![image](https://user-images.githubusercontent.com/10293557/179921180-ebed4287-6dd0-49d4-aa53-2bc3801376bd.png)
正常图片：
![image](https://user-images.githubusercontent.com/10293557/179921475-0f8765f3-550b-4b38-b7e4-f39b8d6e1fb7.png)

**To Reproduce 【复现步骤】**
工程编译后出现的，没做任何修改，linux和windows一样

**Screenshots 【截图】**
截图如上

**Environment 【BUG产生的环境】**
[//]: # (Please complete the following information)
 - OS & Version: Windows10 和 ubuntu
 - Qt Version: 5.12
 - CEF Version: 54 代码中指定的当前版本
 - OSR/NCW Mode: 两个都有

**Comment by tishion** [comment]
看起来是网页的CSS没有拉取下来。挂上调试看看吧。
1. QCefConfig设置调试端口，demo中设置的是9000
2. 启动demo程序
3. 打开一个本机的chrome或者edge，输入http://localhost:9000，然后点击列表中的app就可以使用devtools了

**Comment by xiaoniao88** [comment]
您好，按照上面的做法，发现css 样式是有的，我用cefsimple 查看网页也是正常的，只有在osr 和 ncw 模式下有，很奇怪

**Comment by tishion** [comment]
你的页面地址不方便访问的话，我这边也没办法帮你定位的。

**Comment by xiaoniao88** [comment]
我这边找到原因了，网页样式有些问题，感谢帮忙

**Comment by xiaoniao88** [comment]
我这边找到原因了，网页样式有些问题，感谢帮忙

**Comment by xiaoniao88** [comment]
您好，还是上面的问题，环境是一样的，访问地址后执行java脚本报错，提示cannot reading properties of undefined (reading ‘browser’ ),但使用cefclient 访问地址是正常的，请问这是什么原因呢
