### ISSUE TITLE
[BUG]: 使用vs编译时发生错误

### ISSUE THREAD

**Issue by victor-lcr** [CefView/QCefView#131]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 
按照说明编译时报错
[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
![image](https://user-images.githubusercontent.com/69039383/180587538-f11194c9-aa19-4a1c-981e-6da05596e0ee.png)

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息)
[//]: # (Please complete the following information)
 - OS & Version: Windows 11 x64
 - Qt Version: 5.15.2
 - CEF Version: 102.0.10+gf249b2e+chromium-102.0.5005.115
 - OSR/NCW Mode: 
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)

**Comment by tishion** [comment]
你用的CEF版本比较新，需要自己适配。
