### ISSUE TITLE
linux系统下的下载和打印功能有计划推进吗？

### ISSUE THREAD

**Issue by tonyzhou1985** [CefView/QCefView#132]
linux系统下的下载和打印功能有计划推进吗？

**Comment by tishion** [comment]
下载功能不考虑支持。
打印功能不属于QCefView的内置功能，是开发者根据自己的业务自己实现的，默认右键菜单其实已经包含了打印的按钮。

**Comment by tonyzhou1985** [comment]
可能站在你的角度来看 这两个和qcefview不相干。但是目前我们国产linux系统下 这方面需求量非常大。如果你提升了这块功能，说不定qcefciew能在国产系统中占了一个重要的环节。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sheen ***@***.***&gt;; 
发送时间: 2022年7月25日(星期一) 上午10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CefView/QCefView] linux系统下的下载和打印功能有计划推进吗？ (Issue #132)





 
下载功能不考虑支持。
 打印功能不属于QCefView的内置功能，是开发者根据自己的业务自己实现的，默认右键菜单其实已经包含了打印的按钮。
