### ISSUE TITLE
大佬 请问下 ，如果没有 devtools ，前端想在应用中调试代码，有什么替代方案吗？

### ISSUE THREAD

**Issue by LoveChina-3000** [CefView/QCefView#134]
如题，如果没有 devtools ，前端想在应用中调试代码，有什么替代方案吗？

**Comment by tishion** [comment]
用chrome 或者 edge,挂上调试就行了。

1. QCefConfig设置调试端口，demo中设置的是9000
启动demo程序
2. 打开一个本机的chrome或者edge，输入http://localhost:9000，
3. 然后点击列表中的app就可以使用devtools了

**Comment by LoveChina-3000** [comment]
好的 谢谢
