### ISSUE TITLE
[BUG]: macos 直接把xcode 编译完的 QCefView/build/output/Release/bin/QCefView.framework 放在项目中使用会崩溃

### ISSUE THREAD

**Issue by ZhenZY** [CefView/QCefView#138]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
...

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. 复制 QCefView.framework 到项目目录
2. 项目需要初始化CEF 的地方 include 头文件
3. new QCefContext , QCefSetting, QCefConfig, QCefWidget 都正常
4. addWidget 时开始崩溃

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
正常显示web 页面

**Screenshots 【截图】**
这是 framework 的截图
<img width="531" alt="企业微信截图_38f79e62-775b-4e81-9224-60a55358ab68" src="https://user-images.githubusercontent.com/25266953/184587300-45ecf8b9-22af-477b-8080-2d35d1efe22f.png">

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息)
[//]: # (Please complete the following information)
 - OS & Version: [e.g. Windows/macOS/Linux]macOs 11.3.1
 - Qt Version:5.15.2
 - CEF Version:95
 - OSR/NCW Mode:OFF
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by tishion** [comment]
签名了么

**Comment by ZhenZY** [comment]
您好，我是姜丽珍，您的邮件我已收到，我将尽快回复您，谢谢。

**Comment by ZhenZY** [comment]
日志打错了,是new QCefViewWidget 的时候崩了.这个跟签名有关系吗?需要给应用签名吗?第一次用QT,第一次开放macos 的程序,不了解

**Comment by ZhenZY** [comment]
需要把 CefViewCore.framework 也放在 Frameworks 目录下吗,不过它复制过去也是会崩溃

**Comment by ZhenZY** [comment]
解决了,我的问题,和签名无关

**Comment by tzsh1007** [comment]
> 解决了,我的问题,和签名无关

请问你的问题是如何解决的？
