### ISSUE TITLE
请问需要什么编译环境？

### ISSUE THREAD

**Issue by ajian55** [CefView/QCefView#143]
使用VS2015编译失败，有各种错误。

**Comment by tishion** [comment]
https://github.com/CefView/QCefView/blob/3510a56c5f807e53d27e1ff109780b9524c675d2/CMakeLists.txt#L29

**Comment by ajian55** [comment]
貌似默认设置的就是VC14。但仍然存在问题。

**Comment by ajian55** [comment]
Selecting Windows SDK version  to target Windows 10.0.19043.
The C compiler identification is MSVC 19.0.23026.0
The CXX compiler identification is MSVC 19.0.23026.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Qt SKD dir: C:\Qt\Qt5.9.5\5.9.5\msvc2015_64
CEF SDK dir: C:/QtProjects/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64
===== OFF
*** CEF CONFIGURATION SETTINGS ***
Generator:                    Visual Studio 14 2015
Platform:                     Windows
Project architecture:         x86_64
Binary distribution root:     C:/QtProjects/QCefView-main/CefViewCore/dep/cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64
Visual Studio ATL support:    ON
CEF sandbox:                  OFF
Standard libraries:           comctl32.lib;gdi32.lib;rpcrt4.lib;shlwapi.lib;ws2_32.lib
Compile defines:              __STDC_CONSTANT_MACROS;__STDC_FORMAT_MACROS;WIN32;_WIN32;_WINDOWS;UNICODE;_UNICODE;WINVER=0x0601;_WIN32_WINNT=0x601;NOMINMAX;WIN32_LEAN_AND_MEAN;_HAS_EXCEPTIONS=0;CEF_USE_ATL
Compile defines (Debug):      
Compile defines (Release):    NDEBUG;_NDEBUG
C compile flags:              /MP;/Gy;/GR-;/W4;/WX;/wd4100;/wd4127;/wd4244;/wd4324;/wd4481;/wd4512;/wd4701;/wd4702;/wd4996;/Zi 
C compile flags (Debug):      /M$<IF:$<BOOL:OFF>,T,D>d;/RTC1;/Od 
C compile flags (Release):    /M$<IF:$<BOOL:OFF>,T,D>;/O2;/Ob2;/GF 
C++ compile flags:            /MP;/Gy;/GR-;/W4;/WX;/wd4100;/wd4127;/wd4244;/wd4324;/wd4481;/wd4512;/wd4701;/wd4702;/wd4996;/Zi 
C++ compile flags (Debug):    /M$<IF:$<BOOL:OFF>,T,D>d;/RTC1;/Od 
C++ compile flags (Release):  /M$<IF:$<BOOL:OFF>,T,D>;/O2;/Ob2;/GF 
Exe link flags:                /MANIFEST:NO;/LARGEADDRESSAWARE
Exe link flags (Debug):       /DEBUG 
Exe link flags (Release):      
Shared link flags:             
Shared link flags (Debug):    /DEBUG 
Shared link flags (Release):   
CEF Binary files:             chrome_elf.dll;libcef.dll;libEGL.dll;libGLESv2.dll;snapshot_blob.bin;v8_context_snapshot.bin;vk_swiftshader.dll;vk_swiftshader_icd.json;vulkan-1.dll;swiftshader;d3dcompiler_47.dll
CEF Resource files:           chrome_100_percent.pak;chrome_200_percent.pak;resources.pak;icudtl.dat;locales
Configuring done

**Comment by ajian55** [comment]
严重性	代码	说明	项目	文件	行
错误	C2228	“.y”的左边必须有类/结构/联合	QCefView	C:\QtProjects\QCefView-main\src\details\QCefViewPrivate.cpp	823
错误	C2220	警告被视为错误 - 没有生成“object”文件 (编译源文件 C:\QtProjects\QCefView-main\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64\libcef_dll\wrapper\cef_resource_manager.cc)	libcef_dll_wrapper	C:\QtProjects\QCefView-main\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64\include\base\internal\cef_bind_internal.h	202
错误	C2220	警告被视为错误 - 没有生成“object”文件 (编译源文件 C:\QtProjects\QCefView-main\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64\libcef_dll\wrapper\cef_message_router.cc)	libcef_dll_wrapper	C:\QtProjects\QCefView-main\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64\include\base\internal\cef_bind_internal.h	202
错误	LNK1104	无法打开文件“..\output\Debug\lib\libcef_dll_wrapper.lib”	CefViewWing	C:\QtProjects\QCefView-main\build\CefViewCore\src\LINK	1
错误	C2039	“tolower”: 不是“std”的成员	CefViewCore	C:\QtProjects\QCefView-main\CefViewCore\src\CefView\CefBrowserApp\CefViewBrowserClient.cpp	61
错误	C2665	“QMetaObject::invokeMethod”: 4 个重载中没有一个可以转换所有参数类型	QCefView	C:\QtProjects\QCefView-main\src\details\CCefClientDelegate_ContextMenuHandler.cpp	41
错误	C2665	“QMetaObject::invokeMethod”: 4 个重载中没有一个可以转换所有参数类型	QCefView	C:\QtProjects\QCefView-main\src\details\CCefClientDelegate_ContextMenuHandler.cpp	63
错误	C2665	“QMetaObject::invokeMethod”: 4 个重载中没有一个可以转换所有参数类型	QCefView	C:\QtProjects\QCefView-main\src\details\CCefClientDelegate_ContextMenuHandler.cpp	89
错误	C2665	“QMetaObject::invokeMethod”: 4 个重载中没有一个可以转换所有参数类型	QCefView	C:\QtProjects\QCefView-main\src\details\CCefClientDelegate_LifeSpanHandler.cpp	78
错误	C2665	“QMetaObject::invokeMethod”: 4 个重载中没有一个可以转换所有参数类型	QCefView	C:\QtProjects\QCefView-main\src\details\CCefClientDelegate_LifeSpanHandler.cpp	97
错误	C2665	“QMetaObject::invokeMethod”: 4 个重载中没有一个可以转换所有参数类型	QCefView	C:\QtProjects\QCefView-main\src\details\CCefClientDelegate_LifeSpanHandler.cpp	116
错误	C2039	“position”: 不是“QWheelEvent”的成员	QCefView	C:\QtProjects\QCefView-main\src\details\QCefViewPrivate.cpp	809
错误	C3536	“p”: 初始化之前无法使用	QCefView	C:\QtProjects\QCefView-main\src\details\QCefViewPrivate.cpp	822
错误	C2228	“.x”的左边必须有类/结构/联合	QCefView	C:\QtProjects\QCefView-main\src\details\QCefViewPrivate.cpp	822

**Comment by tishion** [comment]
qt >= 5.12

**Comment by ajian55** [comment]
好的。

**Comment by xiaobingcaicai** [comment]
> 

5.12也不行，QWheelEvent::position是5.14引入到qt的。

**Comment by ajian55** [comment]
收到。谢谢！
