### ISSUE TITLE
DPI 适配解法

### ISSUE THREAD

**Issue by le0zh** [CefView/QCefView#148]
Qt 5.14.2，尝试解决 dpi 问题，使用 `QT_SCALE_FACTOR` 来控制缩放后，发现其他原生 UI 都正常缩放了，`QCefView` 不受控制，，是为什么类？

或者有其他 DPI 适配解法么？

**Comment by tishion** [comment]
DPI适配有什么问题么？你用的什么模式？

**Comment by le0zh** [comment]
用的 OSR 模式，问题如下图：

![image](https://user-images.githubusercontent.com/3633972/190054465-738c4a5b-850a-4482-87bd-05598d57134a.png)

150% 缩放下，QCefView 内的网页内容缩放不太对。

发现  https://github.com/CefView/QCefView/blob/main/src/QCefView.cpp#L271 这里改成 `qreal scaleFactor = devicePixelRatioF();` 就正常了。

另外请教下 OSR 模式下，发现 QCefView 内  web 页面的输入框在使用搜狗中文输入法时，输入法候选字选择框不跟随输入框，是已知问题么，可以解么？

**Comment by tishion** [comment]
> 另外请教下 OSR 模式下，发现 QCefView 内 web 页面的输入框在使用搜狗中文输入法时，输入法候选字选择框不跟随输入框，是已知问题么，可以解么？

不是已知问题，如果只有搜狗输入法有问题，那就是输入法的问题了。 
https://docs.microsoft.com/en-us/windows/win32/tsf/text-services-framework
https://docs.microsoft.com/en-us/windows/win32/tsf/text-services-framework
