### ISSUE TITLE
navigatetourl lead to a crash

### ISSUE THREAD

**Issue by hcaihao** [CefView/QCefView#15]
```
  cefview = new CustomCefView(uri, this);
  cefview->navigateToUrl("http://www.baidu.com/");
```

[0820/163524.140:FATAL:cef_ref_counted.h(325)] Assert failed: ptr_ != 0. 
QCefViewTest.exe has triggered a breakpoint.

I need navigateToUrl without constructor.

**Comment by tishion** [comment]
> ```
>   cefview = new CustomCefView(uri, this);
>   cefview->navigateToUrl("http://www.baidu.com/");
> ```
> 
> [0820/163524.140:FATAL:cef_ref_counted.h(325)] Assert failed: ptr_ != 0.
> QCefViewTest.exe has triggered a breakpoint.
> 
> I need navigateToUrl without constructor.

just pass an empty string or "about:blank" to the construcor
