### ISSUE TITLE
NCW 模式下支持两个 QCefView 重叠么

### ISSUE THREAD

**Issue by le0zh** [CefView/QCefView#151]
RT

实现类似钉钉、飞书全局搜索框的效果：弹出框内嵌一个 QCefView 覆盖在另一个 QCefView 上面。

**Comment by tishion** [comment]
你发个截图看看是什么样的？

**Comment by tishion** [comment]
这个没问题，把1用一个顶级QWidget实现，内部放一个QCefview就行了。
