### ISSUE TITLE
NCW 模式下 QCefView 大小改变时，背景为黑色，能否修改？

### ISSUE THREAD

**Issue by le0zh** [CefView/QCefView#158]
RT 

在初始化时尤为明显，如下图:

![image](https://user-images.githubusercontent.com/3633972/194758393-5c02044e-05c7-4b43-aaeb-8f414a929fc3.png)

黑色过后展示内容，有办法修改这个颜色么。

**Comment by tishion** [comment]
Cef内部窗口自己绘制的。
