### ISSUE TITLE
[建议]: 根据libcef所使用的chromium内核版本来做分支管理

### ISSUE THREAD

**Issue by guobbs** [CefView/QCefView#159]
刚刚接触这个库，做的非常棒，封装布局合理代码质量高，给 @tishion 点赞！

说一下我遇到的问题：
libcef根据不同的版本，API变化频率还是比较高的，比如当前QCefView是基于95.xx版本的，当我使用 104.x 或者 89.x的时候，编译起来就有各种各样的问题，需要改代码适配才能编译通过。

因此提个建议：QCefView 仓库的分支可以参考libcef那样，根据chromiun的版本，来建立维护分支，当 QCefView 官方仓想升级 libcef 版本的时候可以开启新分支，原来的版本也继续保留了。

备注：这个不是bug，我点错 issues 模板了

**Comment by tishion** [comment]
@guobbs 感谢建议，后面如果再更换CEF版本的话就会按照这种方式来管理分支。
