### ISSUE TITLE
Cannot close application in some situations

### ISSUE THREAD

**Issue by Silver-ou** [CefView/QCefView#16]
Hi,
When I only open the main window, I can close it correctly. But if I open some popup window, such as a devtools, I try to close it, the popup windows can close, but the main window cannot close. I found in this situation, for the main_browser_, only execuate the 'DoClose()' function, not execuate 'OnBeforeClose()', in QCefViewBrowserHandler. It makes the application blocked at the lock.

**Comment by tishion** [comment]
Please try with the latest version, I believe this has been fixed alreay.
