### ISSUE TITLE
电脑锁屏再解锁，qcefview加载的页面内容不刷新，点击标题栏中的还原按钮后会白屏

### ISSUE THREAD

**Issue by xiaopan1983** [CefView/QCefView#161]
界面：
程序中有个窗体加载qcefview窗体，然后qcefview窗体再加载h5页面，
qcefview加载的h5页面中有编辑框和文本框（每秒定时刷新显示时间）；

复现操作：
电脑点击“win+L“键进行锁屏操作，然后解除锁屏后，会导致h5页面不刷新，编辑框点击没反应，文本框显示的时间不再跳动；点击标题栏中的还原按钮后会白屏；

恢复操作：
解锁后，如果点击任务栏或点击"alt+tab"，又能正常恢复h5页面刷新；或锁屏前先最小化，然后解锁后又恢复显示，也是可以恢复；

请问下如何保证电脑锁屏后，然后解锁，qcefview加载的h5页面不做恢复操作能正常刷新呢，我这边应该如何处理呢？谢谢~

**Comment by tishion** [comment]
能否按照issue模板补充所有信息？

我这里无法复现你说的问题

**Comment by xiaopan1983** [comment]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)


[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
...


**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
...

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息)
[//]: # (Please complete the following information)
 - OS & Version: [e.g. Windows/macOS/Linux]
 - Qt Version:
 - CEF Version:
 - OSR/NCW Mode:
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by xiaopan1983** [comment]
- @tishion 您好，已按您说的issue模板补充信息，帮忙看看是什么问题；登录页面，锁屏再解锁，登录页面账号和密码输入编辑框不能编辑，看起来就跟编辑框不可用一样的，无法输入或修改里面的内容；

**Comment by tishion** [comment]
这个还真不好说，你可以看看重新进去之后QCefViwing辅助进程还在不在，或者把log发一下。

**Comment by xiaopan1983** [comment]
CefVieWing进程在的，锁屏，然后解除锁屏，debug.log没有特殊日志输出；但是退出程序的时候会报错；

**Comment by xiaopan1983** [comment]
@tishion  您好，使用你们提供的QCefViewTest的demo也有这个问题，打开QCefViewTest测试程序，画面左边编辑框能输入文字，右边图片能不断刷新fps帧率及图像；但是电脑按"win+L"锁屏后，再进去后，QCefViewTest测试程序，画面左边编辑框不能输入文字，右边图片不能刷新fps帧率及图像，不动了；

**Comment by nondeepshit** [comment]
我这边也出现类似的情况, 锁屏后进入页面不能动弹, 将窗口最小化再最大化能恢复.

**Comment by tishion** [comment]
你们没有人说一下使用的是OSR模式还是非OSR模式么？

可以看一下是否因为锁屏后CEF是不是停止绘制了，影响CEF绘制的几个行为：
1. 窗口被隐藏
2. 窗口最小化
以上行为会导致QCefView调用CEF的washiden被调用
https://github.com/CefView/QCefView/blob/47ebc27f9fe3df5127e4540b5e71167109b8f9c1/src/details/QCefViewPrivate.cpp#L649


BTW，我只有周末有时间处理这个项目的问题，所以你们还是自己先尝试定位一下问题。

**Comment by xiaopan1983** [comment]
@tishion 电脑锁屏前后，窗口既没有被隐藏，也没有最小化，但是不会刷新；目前可以其他方式，比如通过激活切换窗体的方式，或最小化的方式解决此问题；

**Comment by tonyzhou1985** [comment]
这个问题 在界面显示出来之后，执行一下 setAttribute(Qt::WA_Mapped)就可以了
