### ISSUE TITLE
[BUG]: 编译出错

### ISSUE THREAD

**Issue by yufewng** [CefView/QCefView#172]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)
我尝试使用VS2019在WIN10下编译源代码，我的QT版本是5.15.2，但是编译时出现在一些错误 和警告，编译无法完成，编译输出时错误与警告如下：

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)

G:\CodeLabs\QT\QCefview\QCefView\src\details\QCefDownloadItemPrivate.cpp(28,6): error C2664: “int cef_time_to_doublet(c
onst cef_time_t *,double *)”: 无法将参数 1 从“cef_basetime_t *”转换为“const cef_time_t *” [G:\CodeLabs\QT\QCefview\QCefView\.bui
ld\windows.x86_64\src\QCefView.vcxproj]

G:\CodeLabs\QT\QCefview\QCefView\src\details\QCefDownloadItemPrivate.cpp(32,6): error C2664: “int cef_time_to_doublet(c
onst cef_time_t *,double *)”: 无法将参数 1 从“cef_basetime_t *”转换为“const cef_time_t *” [G:\CodeLabs\QT\QCefview\QCefView\.bui
ld\windows.x86_64\src\QCefView.vcxproj]

G:\CodeLabs\QT\QCefview\QCefView\src\details\QCefDownloadItemPrivate.cpp(65,30): error C2679: 二元“=”: 没有找到接受“CefBaseTime
”类型的右操作数的运算符(或没有可接受的转换) [G:\CodeLabs\QT\QCefview\QCefView\.build\windows.x86_64\src\QCefView.vcxproj]

G:\CodeLabs\QT\QCefview\QCefView\src\details\QCefDownloadItemPrivate.cpp(69,28): error C2679: 二元“=”: 没有找到接受“CefBaseTime
”类型的右操作数的运算符(或没有可接受的转换) [G:\CodeLabs\QT\QCefview\QCefView\.build\windows.x86_64\src\QCefView.vcxproj]

G:\CodeLabs\QT\QCefview\QCefView\src\details\QCefSettingPrivate.cpp(67,11): error C2039: "plugins": 不是 "CefStructBase<C
efBrowserSettingsTraits>" 的成员 [G:\CodeLabs\QT\QCefview\QCefView\.build\windows.x86_64\src\QCefView.vcxproj]

G:\CodeLabs\QT\QCefview\QCefView\src\details\QCefSettingPrivate.cpp(68,31): error C2039: "plugins": 不是 "CefStructBase<C
efBrowserSettingsTraits>" 的成员 [G:\CodeLabs\QT\QCefview\QCefView\.build\windows.x86_64\src\QCefView.vcxproj]

G:\CodeLabs\QT\QCefview\QCefView\src\details\QCefSettingPrivate.cpp(161,9): error C2039: "plugins": 不是 "CefStructBase<C
efBrowserSettingsTraits>" 的成员 [G:\CodeLabs\QT\QCefview\QCefView\.build\windows.x86_64\src\QCefView.vcxproj]

G:\CodeLabs\QT\QCefview\QCefView\src\details\utils\CommonUtils.cpp(24,32): warning C4996: 'QRegion::rects': Use begin()
/end() instead [G:\CodeLabs\QT\QCefview\QCefView\.build\windows.x86_64\src\QCefView.vcxproj]

**Comment by tishion** [comment]
编译问题请自己解决，一般都是环境问题。

**Comment by linghuzhangmen** [comment]
来自chatgpt的解释

根据我所了解的信息，最新版本的CEF（Chromium Embedded Framework）中，CefBrowserSettings类确实没有名为plugins的成员。但是，可以通过设置CefSettings结构体中的"plugins"成员来启用或禁用CEF的插件功能。

以下是一个示例，展示如何在CEF中启用或禁用插件：

CefSettings settings;
settings.plugins = STATE_ENABLED; //启用插件功能
//或者
settings.plugins = STATE_DISABLED; //禁用插件功能

需要注意的是，插件功能在最新版本的CEF中已经被废弃，建议使用CEF的其他功能来代替插件。如果您仍然需要使用插件功能，建议使用旧版本的CEF。
