### ISSUE TITLE
[BUG]: master 分支 QCefViewTest 运行失败

### ISSUE THREAD

**Issue by le0zh** [CefView/QCefView#179]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)

master 分支 QCefViewTest 运行失败

CrBrowserMain (1): EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. 拉取最新代码
2. ./generate-mac-x86_64.sh 生成 xcdoe 工程
3. 打开 xcode 工程，运行 QCefViewTest
4. 报错

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)

QCefViewTest 能正常运行

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/3633972/202614634-01169a98-86ae-4e24-a84d-b7d4c95f41e1.png">

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode: both 两个都试了
 - OS & Version: MacOS 11.2
 - Qt Version: 5.15.2
 - CEF Version: 104.4.26

**Comment by tishion** [comment]
没有mac的测试环境，你试试更换一下CEF版本？帮忙缩小一下问题范围。

**Comment by le0zh** [comment]
"102.0.10+gf249b2e+chromium-102.0.5005.115" # GOOD
"104.4.18+g2587cf2+chromium-104.0.5112.81" # BAD
"104.4.26+g4180781+chromium-104.0.5112.102" # BAD

**Comment by tishion** [comment]
回退到 "102.0.10+gf249b2e+chromium-102.0.5005.115" # GOOD

**Comment by le0zh** [comment]
是 CEF 版本适配问题么，没能进一步定位到是哪里的问题 😞

**Comment by tishion** [comment]
cef最近几个新版本，各种各样的问题，比如在105开始的版本，debug模式下莫名奇妙的弹debugbreak，你遇到的这个问题有可能是cef又引入了新的破坏性变更，暂时没有时间去看
