### ISSUE TITLE
拖放功能异常

### ISSUE THREAD

**Issue by androrz** [CefView/QCefView#18]
我当前使用的是cef_binary_89.0.12+g2b76680+chromium-89.0.4389.90_windows32这个版本, 
发现DragEvent API  不能正常运行, 拖放目标到放置区域显示一个禁止的图标(见截图).
同样的页面, 在web浏览器是可以正常拖放的, 而且老版本的的cef也是支持拖放的.
![avatar](https://s3.bmp.ovh/imgs/2021/09/cd11f46d16ce0f57.jpg)

**Comment by tishion** [comment]
底层禁用了拖拽功能，如果需要，自行修改。
看这里：
https://github.com/CefView/CefViewCore/blob/3732680e92087331a679f645ca698de8c2286ff7/src/CefView/CefBrowserApp/CefViewBrowserHandler.cpp#L101-L114

**Comment by androrz** [comment]
我看了我当前使用的新老版本OnDragEnter这个方法的实现都是一样的:
bool
QCefViewBrowserHandler::OnDragEnter(CefRefPtr<CefBrowser> browser,
                                    CefRefPtr<CefDragData> dragData,
                                    CefDragHandler::DragOperationsMask mask)
{
  CEF_REQUIRE_UI_THREAD();

  return true;
},

新版本的实现是这样, 我看注释是:
Forbid dragging of URLs and files.
但是从逻辑上看, 最终结果都是返回true.
bool
CefViewBrowserHandler::OnDragEnter(CefRefPtr<CefBrowser> browser,
                                   CefRefPtr<CefDragData> dragData,
                                   CefDragHandler::DragOperationsMask mask)
{
  CEF_REQUIRE_UI_THREAD();

  // Forbid dragging of URLs and files.
  if ((mask & DRAG_OPERATION_LINK) && !dragData->IsFragment()) {
    return true;
  }

  return true;
}

**Comment by mensong** [comment]
> 我当前使用的是cef_binary_89.0.12+g2b76680+chromium-89.0.4389.90_windows32这个版本, 发现DragEvent API 不能正常运行, 拖放目标到放置区域显示一个禁止的图标(见截图). 同样的页面, 在web浏览器是可以正常拖放的, 而且老版本的的cef也是支持拖放的. ![avatar](https://camo.githubusercontent.com/632405c3c27340bd5008acd27965a27d7788fe75974d8f7ab232ecc3a36ffd0a/68747470733a2f2f73332e626d702e6f76682f696d67732f323032312f30392f636431316634366431366365306635372e6a7067)

请问你是怎样解决这个问题的呢？

**Comment by mensong** [comment]
> 

WindowlessRenderingEnabled is set to true by default, set to false to disable the OSR mode:
config.setWindowlessRenderingEnabled(false);
