### ISSUE TITLE
Error during build step VS 2022

### ISSUE THREAD

**Issue by Zusykss** [CefView/QCefView#189]
5> mocs_compilation_Release.obj: error LNK2019: unresolved reference to external symbol "__declspec(dllimport) public: static struct QMetaObject const QWindow::staticMetaObject" (__imp_?staticMetaObject@QWindow@@2UQMetaObject@@B) in function "int __cdecl qRegisterNormalizedMetaType< class QWindow *>(class QByteArray const &,class QWindow * *,enum QtPrivate::MetaTypeDefinedHelper<class QWindow *,1>::DefinedType)" (??$qRegisterNormalizedMetaType@PAVQWindow@@@@@YAHABVQByteArray@@PAPAVQWindow@@ W4DefinedType @ ?$MetaTypeDefinedHelper@PAVQWindow@@$00@QtPrivate@@@Z).
5> mocs_compilation_Release.obj: error LNK2019: reference to unresolved external symbol "__declspec(dllimport) public: static struct QMetaObject const QAction::staticMetaObject" (__imp_?staticMetaObject@QAction@@2UQMetaObject@@B) in function "int __cdecl qRegisterNormalizedMetaType< QAction class *>(QByteArray class const &,QAction class * *,enum QtPrivate::MetaTypeDefinedHelper<QAction class *,1>::DefinedType)" (??$qRegisterNormalizedMetaType@PAVQAction@@@@YAHABVQByteArray@@PAPAVQAction@@W4DefinedType @?$MetaTypeDefinedHelper@PAVQAction@@$00@QtPrivate@@@Z).
5> D:\cxx\QCefView\QCefView\.build\windows.x86\output\Release\bin\QCefView.dll: fatal error LNK1120: unresolved external files: 381
![Screenshot_2](https://user-images.githubusercontent.com/19403619/207120823-017c40f8-033b-4ff5-9581-b5112593d050.png)

**Comment by tishion** [comment]
no detailed information.
