### ISSUE TITLE
1.QCefView 跟搜狗,讯飞输入法冲突，2.QCefWing CPU使用率非常高。

### ISSUE THREAD

**Issue by xinlan0711** [CefView/QCefView#21]
1.在搜狗或者讯飞输入法会与QCefView冲突，导致整个pc处于死机状态。
2.QCefWing CPU使用率非常高经常在20%左右。 
3.调用devtools 需要最小化后刷新才能使用。
请问上述问题怎么解决。。。

**Comment by tishion** [comment]
1&2请用最新版测试，如果还有问题，请重新打开该issue。

3. CEF 提供远程调试功能，只需要进行如下设置：
```cpp
  QCefConfig config(argc, argv);
  config.setRemoteDebuggingPort(9000);
```
启动程序之后，通过Chrome或者Edge访问: http://localhost:9000
即可查看本机所有正在运行的CEF实例，并且可以使用devtools调试功能。

**Comment by wangdemon** [comment]
> 1.在搜狗或者讯飞输入法会与QCefView冲突，导致整个pc处于死机状态。 2.QCefWing CPU使用率非常高经常在20%左右。 3.调用devtools 需要最小化后刷新才能使用。 请问上述问题怎么解决。。。

你是怎么解决的，我也出现过这样的问题。某些时候，程序退出后，CefWing.exe还在后台运行，CPU一直占用30%左右，比谷歌浏览器占用高
