### ISSUE TITLE
能正常打开所有的网页， 但是不播放不了网页里面的视频，有这个功能吗[FEATURE]

### ISSUE THREAD

**Issue by yangkonglin** [CefView/QCefView#225]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rendered by markdown, so there's no need to delete them)

** Feature Description 【特性详细描述】**

[//]: # (请在下面描述所需新特性的详细信息)
[//]: # (Please describe the detailed information about the request feature)
...

**Comment by tishion** [comment]
#10
