### ISSUE TITLE
问题：你好 Linux下编译出来的libcef.so有1.6G？

### ISSUE THREAD

**Issue by ShuJi2012** [CefView/QCefView#230]
我这里的libcef.so编译出来的有1.6G，有什么办法缩小这个库吗？
还有编译出的很多小文件，这些文件没有就运行不了，这个有什么办法处理吗？
谢谢
![image](https://user-images.githubusercontent.com/130046581/231089429-92bfd33c-e773-4950-9c05-7cf98565a79f.png)

**Comment by ShuJi2012** [comment]
我是用的cmake .. &&  cmake --build .编译的，没有更改任何选项

**Comment by tishion** [comment]
> 我是用的cmake .. && cmake --build .编译的，没有更改任何选项

这个不是你/我编译的，项目只是依赖了第三方编译好的cef二进制库文件，如果需要裁剪可以自行编译libcef

**Comment by ShuJi2012** [comment]
thx
