### ISSUE TITLE
如何保存登录信息状态，下次打开依然默认是之前登录的状态[FEATURE]

### ISSUE THREAD

**Issue by michaelkwong** [CefView/QCefView#232]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rendered by markdown, so there's no need to delete them)

** Feature Description 【特性详细描述】**

[//]: # (请在下面描述所需新特性的详细信息)
[//]: # (Please describe the detailed information about the request feature)
...比如我在chrome浏览器登录登录谷歌账号，下次打开依然能登录，我们这个项目应该如何实现呢？

**Comment by ZhouYing-bit** [comment]
QCefView已经实现了，你按下面这个配置就行

`    // 保存登录信息配置
    config.setCachePath("xxx/xx");
    config.setPersistSessionCookies(true);
    config.setPersistUserPreferences(true);
    config.setUserDataPath("xxx/xx");`
