### ISSUE TITLE
ERROR:tcp_socket_win.cc(354)] bind() returned an error: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (0x2740)[BUG]: 

### ISSUE THREAD

**Issue by huangwujie** [CefView/QCefView#234]
窗口直接卡死，靠报错是端口被占用了。这种情况有人遇到过吗？CEF默认窗口是那个呢，和远程调试的窗口有区别不？

**Comment by tishion** [comment]
如果你用的是demo，唯一的设置端口的地方在这里：
https://github.com/CefView/QCefView/blob/f8716084d162560600088a419b94cf7ddd43c540/example/QCefViewTest/main.cpp#L22

看一下是否你的机器上这个端口已经被占用了，可以尝试修改这个端口值。

**Comment by huangwujie** [comment]
我把所有的渲染子进程(CefViewWing.exe)kill掉，窗口清空重新加载url又能继续用了。出现这样的窗口卡死问题还有报错显示端口被占用，会是什么原因导致的呢？
