### ISSUE TITLE
[BUG]: 中文输入法输入异常崩溃

### ISSUE THREAD

**Issue by L-Super** [CefView/QCefView#238]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)

在demo左侧区域的输入框里尝试使用原生输入法（即系统自带输入法）输入中文，会导致程序崩溃退出。

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
...

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)

![image](https://user-images.githubusercontent.com/40905056/234296736-9407ce9d-b457-4a04-b39b-4cf18f128609.png)
**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode: `config.setWindowlessRenderingEnabled(true);`
 - OS & Version: Windows 11
 - Qt Version: Qt5.15.2
 - CEF Version:111.2.7+gebf5d6a+chromium-111.0.5563.148
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by tishion** [comment]
我抽空看，现在维护这个项目的时间比较少

**Comment by ZhouYing-bit** [comment]
确实是会崩溃，我也遇到了，我尝试下能不能修复

**Comment by L-Super** [comment]
bug fixed on `113.3.1+g525fa10+chromium-113.0.5672.128 / Chromium 113.0.5672.128`

**Comment by tishion** [comment]
Fixed by commit 2fbe218393f149e7a419a49a1386b245745c1649
