### ISSUE TITLE
[BUG]: devtools窗口一闪而过

### ISSUE THREAD

**Issue by mensong** [CefView/QCefView#247]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
...
之前showdevtools可以展示的，获取新的代码后，发现devtools窗口一闪而过就不见了。
进过排查，发现是新增的以下代码导致的：

void
QCefViewPrivate::onCefBrowserCreated(CefRefPtr<CefBrowser> browser, QWindow* window)
{
  // capture the browser
  pCefBrowser_ = browser;

  // #if defined(CEF_USE_OSR)
  if (isOSRModeEnabled_) {
    // notify the visibility and size
    pCefBrowser_->GetHost()->WasHidden(!q_ptr->isVisible());
    pCefBrowser_->GetHost()->WasResized();
    connect(this, SIGNAL(updateOsrFrame()), q_ptr, SLOT(update()));

    // monitor the screenChanged signal from the top-level window
    disconnect(this, SLOT(onViewScreenChanged(QScreen*)));
    if (q_ptr->window()->windowHandle()) {
      connect(q_ptr->window()->windowHandle(),    //
              SIGNAL(screenChanged(QScreen*)),    //
              this,                               //
              SLOT(onViewScreenChanged(QScreen*)) //
      );
    }
  } else { // #else
    // create QWidget from cef browser widow, this will re-parent the CEF browser window
    QWidget* browserWidget = QWidget::createWindowContainer(
      window,
      q_ptr,
      Qt::CustomizeWindowHint | Qt::FramelessWindowHint | Qt::WindowTransparentForInput | Qt::WindowDoesNotAcceptFocus);
    Q_ASSERT_X(browserWidget, "QCefViewPrivateNCW::createBrowser", "Failed to create QWidget from cef browser window");
    if (!browserWidget) {
      qWarning("Failed to create QWidget from cef browser window");
      browser->GetHost()->CloseBrowser(true);
      return;
    }

    // capture the resource
    ncw.qBrowserWindow_ = window;
    ncw.qBrowserWidget_ = browserWidget;

    // monitor the focus changed event globally
    connect(qApp, &QApplication::focusChanged, this, &QCefViewPrivate::onAppFocusChanged);

    // initialize the layout and add browser widget to the layout
    QVBoxLayout* layout = new QVBoxLayout();
    layout->setContentsMargins(0, 0, 0, 0);
    layout->setSpacing(0);
    layout->addWidget(ncw.qBrowserWidget_);
    q_ptr->setLayout(layout);

    // update mask
    UpdateCefWindowMask(ncw.qBrowserWindow_, q_ptr->mask());
  }
  // #endif

  // emit signal
  q_ptr->browserCreated(q_ptr);
}

虽然知道哪些代码导致的，但是不知道怎么改，麻烦看一下，谢谢。

**Comment by mensong** [comment]
看了一下，原来正常的情况下，发起调用的地方是这样写的：
`QMetaObject::invokeMethod(
    pCefViewPrivate_,
    [=]() {
      CefRefPtr<CefBrowser> b(browser);
      if (b->IsPopup())
        pCefViewPrivate_->onCefPopupBrowserCreated(b, w);
      else
        pCefViewPrivate_->onCefMainBrowserCreated(b, w);
    },
    c);`
后来改成这样了：
`QMetaObject::invokeMethod(
    pCefViewPrivate_,
    [=]() {
        pCefViewPrivate_->onCefBrowserCreated(browser, w);
    },
    c);`
请问是因为什么原因不区分IsPopup()的呢？

**Comment by tishion** [comment]
拉一下最新代码看看，devtools是没有问题的。

**Comment by mensong** [comment]
测试OK了
