### ISSUE TITLE
[BUG]: macOS 系统 Qt6.5 环境编译报错 (std::filesystem::path)

### ISSUE THREAD

**Issue by fancyop** [CefView/QCefView#265]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
macOS 系统 Qt6.5环境编译报错

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. 克隆代码
````
git clone --recursive https://github.com/CefView/QCefView.git
````
2. 配置编译环境
````
cd QCefView
export QTDIR=~/Qt-6.5/6.5.1/macos
````
3. 编译
````
./generate-mac-x86_64.sh
cmake --build .build/macos.x86_64
````

**Expected behavior 【正确的预期行为】**

cmake过程编译失败，输出内容
````
** BUILD FAILED **

In file included from /Users/XXXX/Qt-6.5/6.5.1/macos/lib/QtCore.framework/Headers/qdir.h:8:
/Users/XXXX/Qt-6.5/6.5.1/macos/lib/QtCore.framework/Headers/qfile.h:31:58: error: 
      'path' is unavailable: introduced in macOS 10.15
inline QString fromFilesystemPath(const std::filesystem::path &path)
                                                         ^
In file included from /Users/XXXX/workspace/QCefView/src/details/QCefSettingPrivate.cpp:6:
In file included from /Users/XXXX/Qt-6.5/6.5.1/macos/lib/QtCore.framework/Headers/QDir:1:
In file included from /Users/XXXX/Qt-6.5/6.5.1/macos/lib/QtCore.framework/Headers/qdir.h:8:
In file included from /Users/XXXX/Qt-6.5/6.5.1/macos/lib/QtCore.framework/Headers/qfile.h:13:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 
      'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/XXXX/workspace/QCefView/src/details/QCefSettingPrivate.cpp:6:
In file included from /Users/XXXX/Qt-6.5/6.5.1/macos/lib/QtCore.framework/Headers/QDir:1:
In file included from /Users/XXXXQt-6.5/6.5.1/macos/lib/QtCore.framework/Headers/qdir.h:8:
/Users/XXXX/Qt-6.5/6.5.1/macos/lib/QtCore.framework/Headers/qfile.h:36:40: error: 
      'native' is unavailable: introduced in macOS 10.15
    return QString::fromStdString(path.native());

。。。。省略


The following build commands failed:
	CompileC /Users/XXXX/workspace/QCefView/.build/macos.x86_64/build/QCefView.build/Debug/Objects-normal/x86_64/QCefSettingPrivate.o /Users/XXXX/workspace/QCefView/src/details/QCefSettingPrivate.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'QCefView' from project 'QCefView')
(1 failure)
````

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
...

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode:
 - OS & Version: macOS 版本13.3.1
 - Qt Version: Qt 6.5.1
 - CEF Version: 同 commit: **1d1c8cc8376245b298fdc9786c5ddc8fc4fe83e6**

**Comment by tishion** [comment]
这个应该是Qt的问题

**Comment by Armmegon** [comment]
Did you managed to solved that issue @tishion @fancyop  ?

**Comment by fancyop** [comment]
> Did you managed to solved that issue @tishion @fancyop  ?

You can try to solve it by referring to the following steps.

https://blog.csdn.net/fancyop/article/details/132687223

**Comment by Armmegon** [comment]
@fancyop I tried but still no difference. Did you managed to solve it, if so how? This article was on a Chinese language maybe   I am not sure, can you please give some brief guidance if you managed to solve it ?
