### ISSUE TITLE
[BUG]: NCW模式下，多标签页切换页面，会有闪烁黑屏的情况

### ISSUE THREAD

**Issue by L-Super** [CefView/QCefView#269]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)

实现了一个多标签页的类浏览器应用，发现在多标签页情况下，进行标签页新建、页面的切换时，在切换的过程中，经常会有窗口闪烁，轻微黑屏的情况。

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
不出现闪烁黑屏的情况

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
![动画](https://github.com/CefView/QCefView/assets/40905056/86cbe975-a3ba-406f-a600-a04fbd68d46a)

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode:NCW
 - OS & Version: Windows
 - Qt Version:5.15.2
 - CEF Version:cef_binary_113.3.1+g525fa10+chromium-113.0.5672.128_windows64
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
OSR模式下，暂未发现此现象

**Comment by L-Super** [comment]
> 这个问题框架层面不一定好解决，改变开发思路可能是更好的方法。
> 比如可以预留一个空白窗口改成你想要的颜色背景，每当有新窗口加载的时候，页面加载成功前先展示预留的窗口，加载成功后再用真实窗口来替换掉。

这个方法表可能只是闪烁的背景色变了，也没起到治标的作用

**Comment by HeGangSZ** [comment]
我们的项目也出现了类似的问题，用cef的源码demo是没有这个问题的，OSR模式会有性能消耗较大的问题，希望作者关注下

**Comment by L-Super** [comment]
> > > 这个问题框架层面不一定好解决，改变开发思路可能是更好的方法。
> > > 比如可以预留一个空白窗口改成你想要的颜色背景，每当有新窗口加载的时候，页面加载成功前先展示预留的窗口，加载成功后再用真实窗口来替换掉。
> > 
> > 这个方法表可能只是闪烁的背景色变了，也没起到治标的作用
>   
> 其实我的项目也遇到这样的问题，大概知道原因，在这种多标签页中使用了QLayout来管理当前web页面，这个切换过程中是会引起QLayout重新布局，会让web页重这个窗口重新渲染一次。这个黑黑的背景应该就是 web 页面原生窗口的背景色。
> 
> 闪的原因是web页面发生了重绘，要解决就是要避免触发窗口无意义的重绘。这里要就小心处理QLayout的使用。

我使用的qtabwidget去添加view，这种情形下，有什么解决方案吗

**Comment by L-Super** [comment]
Bug fixed by 6be6affcde85cfd926273545282174cc2229f955. The problem was resolved after the NCW refactoring.

By the way, it's also OK:
```cpp
windowInfo.SetAsChild((CefWindowHandle)ncw.qBrowserWindow_->winId(), { 0, 0, view->maximumWidth(), view->maximumHeight() });
```

**Comment by ZhouYing-bit** [comment]
![image](https://github.com/CefView/QCefView/assets/13702789/45f3f68a-4da5-4e45-9282-68c4b46e92c8)

是不是这里代码处理引起的问题，窗口不可见时被resize(0, 0),再次可见时又重新resize到窗口大小，必然会出现闪烁。

**Comment by L-Super** [comment]
> ![image](https://private-user-images.githubusercontent.com/13702789/288645234-45f3f68a-4da5-4e45-9282-68c4b46e92c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzM0OTEsIm5iZiI6MTcwMTkzMzE5MSwicGF0aCI6Ii8xMzcwMjc4OS8yODg2NDUyMzQtNDVmM2Y2OGEtNGRhNS00ZTQ1LTkyODItNjhjNGI0NmU5MmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA3MTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMDc1N2EwMDdhYWJiOWU2ZjFhYTA1ODJkYzg1ZmQyNzRlYTBmYzIyMzYxYjNlOWU3ZDczNWZmZjYxYWUzOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XhT6gb_7DvW3_3gxrxJS8HltqzEcVn3kflGI3pUJ1is)
> 
> 是不是这里代码处理引起的问题，窗口不可见时被resize(0, 0),再次可见时又重新resize到窗口大小，必然会出现闪烁。

尝试了一下，注释了这里的代码后，似乎没有闪烁了，有待进一步观察研究

**Comment by goodstarts** [comment]
<img width="807" height="522" alt="Image" src="https://github.com/user-attachments/assets/fc6ed282-f664-4856-b2bc-8d297e1b83f4" />

@L-Super  大神你好，我现在是基于qcefview1.2.1版本ncw模式进行开发，将qcefview放置在cefviewwidget中，在一个页面内开启多个cefviewwidget会出现这种闪烁黑屏的现象，我看qcefview中的源码有把这部分内容注释掉。

**Comment by goodstarts** [comment]
> > <img alt="Image" width="807" height="522" src="https://private-user-images.githubusercontent.com/128124725/505866903-fc6ed282-f664-4856-b2bc-8d297e1b83f4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE1NTI4NTIsIm5iZiI6MTc2MTU1MjU1MiwicGF0aCI6Ii8xMjgxMjQ3MjUvNTA1ODY2OTAzLWZjNmVkMjgyLWY2NjQtNDg1Ni1iMmJjLThkMjk3ZTFiODNmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAyN1QwODA5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzZjM2E2ZTY3YmUwNGYwMmQ5YThiNzVmYTQxOGQxZjFjNzkwOTBhY2Y0ZjAzMzk1ODEzMmEwZjliZWNkMTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yqObk65VEBMcZVVwCEGRG7rW7ZNXiyjVBEPfzHKhhtE">
> > [[@L-Super](https://github.com/L-Super)](https://github.com/L-Super) 大神你好，我现在是基于qcefview1.2.1版本ncw模式进行开发，将qcefview放置在cefviewwidget中，在一个页面内开启多个cefviewwidget会出现这种闪烁黑屏的现象，我看qcefview中的源码有把这部分内容注释掉。
> 
> 可以尝试一下最新版本

好的，我试下，谢谢您的解答
