### ISSUE TITLE
按像素垂直滚动

### ISSUE THREAD

**Issue by ZhouYing-bit** [CefView/QCefView#271]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rendered by markdown, so there's no need to delete them)

**使用鼠标滚动网页时，scrollBar是跳跃式变化，给人的感觉是卡顿掉帧，能不能像TableView那样支持设置滚动模式setHorizontalScrollMode(QAbstractItemView::ScrollPerPixel);**

[//]: # (请在下面描述所需新特性的详细信息)
[//]: # (Please describe the detailed information about the request feature)
...

**Comment by tishion** [comment]
平缓滚动不支持

**Comment by ZhouYing-bit** [comment]
大佬能简单解释下不支持的原因吗
@tishion

**Comment by tishion** [comment]
这个没有太多可以解释的，你看看Windows上的Edge/Chrome浏览器是不是支持平滑滚动。
