### ISSUE TITLE
[BUG]: Linux系统下Release模式，libqcefview、libcef动态库仍为debug版本

### ISSUE THREAD

**Issue by L-Super** [CefView/QCefView#273]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
当我使用Qt Creator选择Release模式，或者命令行执行CMake显式指定Release模式，而且终端cmake输出的信息也是显示Release版本

但编译后output里的动态库仍然为debug版本的，占用空间很大，libcef.so占用1G大小。与cef Debug目录下的so文件一致。

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
```
cmake .. -DCMAKE_BUILD_TYPE=Release
make
```

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
...

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode: OSR
 - OS & Version: Linux
 - Qt Version:Qt 6.5
 - CEF Version: cef_binary_113.3.1+g525fa10+chromium-113.0.5672.128_windows64
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by tishion** [comment]
这个问题，我感觉是不是你看错了

**Comment by L-Super** [comment]
> 这个问题，我感觉是不是你看错了

是的，我弄错了

**Comment by man345** [comment]
是release的库就是这么大吗？有一个多G

**Comment by L-Super** [comment]
> 是release的库就是这么大吗？有一个多G

不记得了，strip命令可以减少库大小

**Comment by man345** [comment]
windows下的库还有办法裁剪吗？楼主

**Comment by L-Super** [comment]
> windows下的库还有办法裁剪吗？楼主
> 

Windows大小还好吧，再裁剪就得从源码下手了
