### ISSUE TITLE
[BUG]: Linux系统下，上传文件无法调用系统文件对话框

### ISSUE THREAD

**Issue by L-Super** [CefView/QCefView#274]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
在UOS系统下，网页的上传文件功能无法使用，没能调用对话框进行文件上传操作。

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
打开如”[文叔叔](https://www.wenshushu.cn/)“文件上传网站，选择上传，没有响应。

日志有如下错误信息：
```
[0602/113218.735271:ERROR:web_contents_delegate.cc(164)] Not implemented reached in virtual FullscreenState content::WebContentsDelegate::GetFullscreenState(const WebContents *) const
[0602/113218.735397:ERROR:file_dialog_manager.cc(421)] Default dialog implementation is not available; canceling the file dialog
```

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
能弹出系统的文件管理对话框，进行文件的选择，上传等操作。

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode:OSR
 - OS & Version: Windows
 - Qt Version: Qt 6.5
 - CEF Version:cef_binary_113.3.1+g525fa10+chromium-113.0.5672.128_windows64
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
Windows下能够正常弹出文件管理对话框，如点击选择文件按钮，打开对话框
![image](https://github.com/CefView/QCefView/assets/40905056/2be4cb22-85f9-4dbd-ab7f-6793432852c4)

**Comment by tishion** [comment]
这个你应该给CEF提，或者你自己实现。

**Comment by AnsunHo** [comment]
作者能分享一下问题是怎么解决的吗？

**Comment by L-Super** [comment]
> 作者能分享一下问题是怎么解决的吗？
> 

最新提交也解决此问题

**Comment by L-Super** [comment]
> 作者能分享一下问题是怎么解决的吗？
> 

3a72a3a59e3f9b0322573a69ada35aa5ac0cd339 已解决

**Comment by AnsunHo** [comment]
> > 作者能分享一下问题是怎么解决的吗？
> 
> [3a72a3a](https://github.com/CefView/QCefView/commit/3a72a3a59e3f9b0322573a69ada35aa5ac0cd339) 已解决

在linux操作系统下，直接使用原生 html的表单input type="file" 上传文件，是无法弹出原生的文件选择框吗？

**Comment by L-Super** [comment]
> 
> 
> 
> 
> > > 作者能分享一下问题是怎么解决的吗？
> > 
> > [3a72a3a](https://github.com/CefView/QCefView/commit/3a72a3a59e3f9b0322573a69ada35aa5ac0cd339) 已解决
> 
> 在linux操作系统下，直接使用原生 html的表单input type="file" 上传文件，是无法弹出原生的文件选择框吗？
> 

可自行尝试一下

**Comment by goodstarts** [comment]
> > > > 作者能分享一下问题是怎么解决的吗？
> > > 
> > > 
> > > [3a72a3a](https://github.com/CefView/QCefView/commit/3a72a3a59e3f9b0322573a69ada35aa5ac0cd339) 已解决
> > 
> > 
> > 在linux操作系统下，直接使用原生 html的表单input type="file" 上传文件，是无法弹出原生的文件选择框吗？
> 
> 可自行尝试一下

您好，请问你是怎么实现的

**Comment by goodstarts** [comment]
> > > > > > 作者能分享一下问题是怎么解决的吗？
> > > > > 
> > > > > 
> > > > > [3a72a3a](https://github.com/CefView/QCefView/commit/3a72a3a59e3f9b0322573a69ada35aa5ac0cd339) 已解决
> > > > 
> > > > 
> > > > 在linux操作系统下，直接使用原生 html的表单input type="file" 上传文件，是无法弹出原生的文件选择框吗？
> > > 
> > > 
> > > 可自行尝试一下
> > 
> > 
> > 您好，请问你是怎么实现的
> 
> 隔得太久了，有点忘了，可以看看这个提交 [f736b64](https://github.com/CefView/QCefView/commit/f736b644663c233d48351ff2a42b3c8666aaae81)，也许能有帮助

您好，你之前也是通过调用网页自带的input方法来上传文件，后面上传不来才改用的这个QFiledialog来实现吗

**Comment by L-Super** [comment]
> 
> 您好，你之前也是通过调用网页自带的input方法来上传文件，后面上传不来才改用的这个QFiledialog来实现吗

不是，是网页上传文件时，无法启动文件管理器，导致无法选择对应的文件
