### ISSUE TITLE
[BUG]: 发现一个问题，OSR 离屏渲染模式 不支持从系统拖拽文件到web页面上。

### ISSUE THREAD

**Issue by w08** [CefView/QCefView#278]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
...
发现一个问题，OSR 离屏渲染模式 不支持从系统拖拽文件到web页面上。

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1、加载本地的测试web页面
2、非离屏模式正常，离屏渲染模式貌似没有处理鼠标拖入
3、拖入文件，无任何响应。

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
...

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...‘
截图仅供参考
![2023 06 09_ 2668154311b82ad54818356ea5fab5f1](https://github.com/CefView/QCefView/assets/55098452/2c8c9d52-5bc3-4ca4-832d-a8219ea453d0)

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode:OSR
 - OS & Version: [e.g. Windows/macOS/Linux] Windows
 - Qt Version:5.12
 - CEF Version: 89 64位
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by L-Super** [comment]
对QCefViewTest程序做了什么修改吗？我的不管是osr还是ncw，拖拽都是处于禁用状态，还是跟cef版本相关？我的cef版本是113的

**Comment by w08** [comment]
是啊，让他加载了一个可以拖入文件的测试页面，osr模式，禁用我打开了，ncw模式可以拖动文件 功能正常，osr模式，这块功能是从core层开始都没实现吧？ 有打算做吗

**Comment by JacksonXu761** [comment]
> 是啊，让他加载了一个可以拖入文件的测试页面，osr模式，禁用我打开了，ncw模式可以拖动文件 功能正常，osr模式，这块功能是从core层开始都没实现吧？ 有打算做吗
> 
> 另外问个问题，目前的版本，支持osr模式和ncw模式共存吗

并非做不了，而是他只是提供一个类似于接口一样的功能，他并不知道你外部的句柄，所以没有办法做这个操作
