### ISSUE TITLE
[BUG]: 不能正常加载摄像头数据

### ISSUE THREAD

**Issue by bigcwu** [CefView/QCefView#280]
[//]: #  
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)

1. 我在main函数中和添加如下代码
`config.addCommandLineSwitch("enable-system-flash"); // flash
  config.addCommandLineSwitch("enable-speech-input"); //语音输入
  config.addCommandLineSwitch("enable-media-stream");
  config.addCommandLineSwitch("disable-gpu");
  config.addCommandLineSwitch("ignore-certificate-errors");
  config.addCommandLineSwitch("enable-usermedia-screen-capturing");
  config.addCommandLineSwitch("enable-experimental-web-platform-features");
`
程序不能正常加载摄像头的视频流“https://vvclass.shinevv.com/?s=eyJyb29tX2lkIjoiMTA0NDk1IiwgInBhc3N3b3JkIjoiMjIyMjIyMjIiLCAibmlja05hbWUiOiLmiJHmmK%2FlsI%2Fnmb0iIH0%3D”

2. 另外我在CefViewBrowserApp::OnBeforeCommandLineProcessing函数添加如下代码也不生效：
`command_line->AppendSwitch("enable-system-flash"); // flash
  command_line->AppendSwitch("enable-speech-input"); //语音输入
  command_line->AppendSwitch("enable-media-stream");
  command_line->AppendSwitch("disable-gpu");
  command_line->AppendSwitch("ignore-certificate-errors");
  command_line->AppendSwitch("enable-usermedia-screen-capturing");
  command_line->AppendSwitch("enable-experimental-web-platform-features");`

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. 我在cefSimple中用如下代码进行测试可以正常打开摄像头
`void
SimpleApp::OnBeforeCommandLineProcessing(const CefString& process_type, CefRefPtr<CefCommandLine> command_line)
{
      command_line->AppendSwitch("enable-system-flash"); // flash
      command_line->AppendSwitch("enable-speech-input"); //语音输入
      command_line->AppendSwitch("enable-media-stream");
      command_line->AppendSwitch("disable-gpu");
      command_line->AppendSwitch("ignore-certificate-errors");
      command_line->AppendSwitch("enable-usermedia-screen-capturing");
      command_line->AppendSwitch("enable-experimental-web-platform-features");
}`
**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
...

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode:
 - OS & Version: [e.g. Windows/macOS/Linux]
 - Qt Version:
 - CEF Version:
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by tishion** [comment]
前端获取设备的方法有问题吧，标准被WebRTC页面都是没问题的
