### ISSUE TITLE
Cross-platform compilation on windows and linux for different architectures of cpu  

### ISSUE THREAD

**Issue by heary29** [CefView/QCefView#29]
Hello, I am currently compiling this project with source code, but I found that the cmake used in the construction project is only wini386/winx64/arch64/Linux x86_64/Linux aarch64 for linux and window. If I want the compiled library files or sample programs, it can be found in Other architectures such as running on mips, what needs to be done? 
您好，目前正在用源码编译这个项目，但是我发现构建工程使用的cmake 关于linux和window只有wini386/winx64/arch64/Linux x86_64/Linux aarch64,如果我想要编译后的库文件或者示例程序能在其他架构比如mips上运行，需要怎样操作？

**Comment by tishion** [comment]
hi @heary2,

First of all you need to confirm whether the CEF is supported on your target architecture, please refer to https://cef-builds.spotifycdn.com/index.html

As you can see currently lib CEF only supports the following paltform+architecture metrics
Linux 32-bit
Linux 64-bit
Linux ARM
Linux ARM64
MacOS ARM64
MacOS 64-bit
Windows 32-bit
Windows 64-bit
Windows ARM64

then you need to make sure Qt is supported on your target architecture.

If CEF or Qt doesn't support your target architecture, you need to compile it first. Once you get all  dependencies ready, you need to modify the CMake files in QCefView and CefViewCore repo.

**Comment by qsc-louissadava** [comment]
@tishion 
Do you have any advice on getting the CefViewCore repo cross compiled? 
I am building on an Ubuntu x86_64 system for an embedded aarch64linux system. I think the Linux ARM64 CEF will work for me. 
I created a new script 'generate-linux-arm64.sh' that looks like this:
```
#!/bin/bash

BUILD_PROJECT=1

BUILD_DIR="$(pwd)/.build/linux.arm64"

while getopts bi flag
do
    case "${flag}" in
        b) BUILD_PROJECT=1;;
    esac
done

echo ============== Config project ==============
cmake -G "Unix Makefiles" -S . -B "${BUILD_DIR}" -DCMAKE_BUILD_TYPE=Release -DPROJECT_ARCH=arm64 -DBUILD_DEMO=OFF -DUSE_SANDBOX=OFF -DCMAKE_INSTALL_PREFIX:PATH="$(pwd)/out/linux.arm64" $*

if [ ${BUILD_PROJECT} -eq 1 ] 
then
    echo ============== Build project ==============
    cmake --build "${BUILD_DIR}"
fi
```
Added these lines to the root ./CMakeLists.txt:25:
```
# Setup the cross compile for TSC Linux aarch64
set(CMAKE_TOOLCHAIN_FILE /home/louis/sdb/Louis/qsys/tools/bin/aarch64-linux-gnu.cmake)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_CROSSCOMPILING "TRUE")
```
And added a new case in the same CMakeLists.txt:81:
```
  elseif(PROJECT_ARCH STREQUAL "arm64")
    add_compile_options(-m64)
    add_link_options(-m64)
    target_link_options(-maarch64linux)
    set(CMAKE_LINKER /home/louis/sdb/Louis/qsys/toolchain/aarch64-linux-gnu/bin/ld)
```

But I'm getting linker errors: 
`/home/louis/sdb/Louis/qsys/toolchain/aarch64-linux-gnu/bin/ld: CMakeFiles/CefViewWing.dir/Shared/Common/CefViewCoreLog.cpp.o: error adding symbols: file in wrong format`

Seems like CefViewCore isn't getting cross compiled? Where do I set my toolchain file for that build?

**Comment by tishion** [comment]
> @tishion Do you have any advice on getting the CefViewCore repo cross compiled? I am building on an Ubuntu x86_64 system for an embedded aarch64linux system. I think the Linux ARM64 CEF will work for me. I created a new script 'generate-linux-arm64.sh' that looks like this:
> 
> ```
> #!/bin/bash
> 
> BUILD_PROJECT=1
> 
> BUILD_DIR="$(pwd)/.build/linux.arm64"
> 
> while getopts bi flag
> do
>     case "${flag}" in
>         b) BUILD_PROJECT=1;;
>     esac
> done
> 
> echo ============== Config project ==============
> cmake -G "Unix Makefiles" -S . -B "${BUILD_DIR}" -DCMAKE_BUILD_TYPE=Release -DPROJECT_ARCH=arm64 -DBUILD_DEMO=OFF -DUSE_SANDBOX=OFF -DCMAKE_INSTALL_PREFIX:PATH="$(pwd)/out/linux.arm64" $*
> 
> if [ ${BUILD_PROJECT} -eq 1 ] 
> then
>     echo ============== Build project ==============
>     cmake --build "${BUILD_DIR}"
> fi
> ```
> 
> Added these lines to the root ./CMakeLists.txt:25:
> 
> ```
> # Setup the cross compile for device Linux aarch64
> set(CMAKE_TOOLCHAIN_FILE /home/louis/sdb/Louis/proj/tools/bin/aarch64-linux-gnu.cmake)
> set(CMAKE_SYSTEM_PROCESSOR arm64)
> set(CMAKE_CROSSCOMPILING "TRUE")
> ```
> 
> And added a new case in the same CMakeLists.txt:81:
> 
> ```
>   elseif(PROJECT_ARCH STREQUAL "arm64")
>     add_compile_options(-m64)
>     add_link_options(-m64)
>     target_link_options(-maarch64linux)
>     set(CMAKE_LINKER /home/louis/sdb/Louis/proj/toolchain/aarch64-linux-gnu/bin/ld)
> ```
> 
> But I'm getting linker errors: `/home/louis/sdb/Louis/proj/toolchain/aarch64-linux-gnu/bin/ld: CMakeFiles/CefViewWing.dir/Shared/Common/CefViewCoreLog.cpp.o: error adding symbols: file in wrong format`
> 
> Seems like CefViewCore isn't getting cross compiled? Where do I set my toolchain file for that build?

try to cross-compile CEF demo with your dev environment and see if there is any errors?

**Comment by qsc-louissadava** [comment]
@tishion Where is CEF demo? This: https://github.com/iboB/cef-demos? Or this: https://github.com/chromiumembedded/cef-project/tree/master/examples/minimal?

**Comment by tishion** [comment]
https://cef-builds.spotifycdn.com/index.html
