### ISSUE TITLE
Core代码编译不过，导致整体编译不出来。

### ISSUE THREAD

**Issue by beanhacker** [CefView/QCefView#294]
老顽童，写的锤子垃圾代。还不及时发布编译版本，自以为是，让别人自己编译，各种编译不过！
自以为自己的代码多么优秀，一键可完成，实际极度垃圾，各种异常，浪费精力，废品！果断不玩！！

**Comment by tishion** [comment]
请问你的主子是谁？我是不是哪里得罪你的主子了？
