### ISSUE TITLE
【问题】你好，我是否有办法控制侧面的滚动条的大小？

### ISSUE THREAD

**Issue by Shu7i** [CefView/QCefView#296]
你好大佬，现在在嵌入式设备上屏幕右边的滚动条太小了按不到，有接口去操作右边的滚动条放大吗？

**Comment by tishion** [comment]
需要在web中通过css样式来自定义滚动条。

https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_custom_scrollbar2
