### ISSUE TITLE
[BUG]: QCefViewTest程序NewBrowser白屏

### ISSUE THREAD

**Issue by ifpelset** [CefView/QCefView#305]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
Ubuntu 18.04下QCefViewTest程序NewBrowser白屏

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. 运行QCefViewTest
2. 点击NewBrowser

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
正确渲染出网页

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
![cef](https://github.com/CefView/QCefView/assets/5791303/7742839c-9392-4a25-a0ed-ede64b555d2e)

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode: OSR
 - OS & Version: Ubuntu 18.04
 - Qt Version: 5.15.2
 - CEF Version: 102.0.10
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by L-Super** [comment]
https://github.com/CefView/QCefView/blob/212b708f91219344d5cde53644d0965cf032a4de/example/QCefViewTest/main.cpp#L29
改为true，因为Linux下NCW还不支持

**Comment by tishion** [comment]
这个应该是用户的网络问题，github.io的访问是需要梯子的。

**Comment by ifpelset** [comment]
Firefox应该是可访问的。

**Comment by AIR-HH** [comment]
> > Firefox应该是可访问的。
> 
> 白屏有两种原因
> 
> * 网络问题无法加载，如Google
> * 采用的NCW模式（旧版本不支持Linux 下NCW）
> 
> 若排除网络问题，可以尝试更新QCefView，最新提交已支持NCW模式。

我之前用ncw模式，用命令启动的时候要先执行xhost +,然后才能显示，不然都是白屏

**Comment by L-Super** [comment]
> > > Firefox应该是可访问的。
> > 
> > 白屏有两种原因
> > 
> > * 网络问题无法加载，如Google
> > * 采用的NCW模式（旧版本不支持Linux 下NCW）
> > 
> > 若排除网络问题，可以尝试更新QCefView，最新提交已支持NCW模式。
> 
> 我之前用ncw模式，用命令启动的时候要先执行xhost +,然后才能显示，不然都是白屏

6be6affcde85cfd926273545282174cc2229f955 提交之后支持NCW，显示正常
