### ISSUE TITLE
[BUG]:  MACOS arm64  QCefViewTest 调试运行报错

### ISSUE THREAD

**Issue by LiYaLinIsLaoSix** [CefView/QCefView#315]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)

1、master 分支 QCefViewTest 运行失败

        libcef_dll_dylib
        NO_SANITIZE("cfi-icall") void cef_do_message_loop_work() {
          g_libcef_pointers.cef_do_message_loop_work();
        }
        
        提示
        CrBrowserMain (1): EXC_BREAKPOINT (code=1, subcode=0x126d2e80c)
        
        0914/151303.479808:ERROR:mach_port_rendezvous.cc(311)] bootstrap_look_up com.cefview.cefviewwing.MachPortRendezvousServer.20213: Unknown service name (1102)
        [0914/151303.479839:ERROR:mach_port_rendezvous.cc(311)] bootstrap_look_up com.cefview.cefviewwing.renderer.MachPortRendezvousServer.20213: Unknown service name (1102)
        
2、如果忽略调试错误，直接点击 QCefViewTest.app和集成的app，web页面可以正常显示，但是鼠标滚动和滚动条不可用；

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. 拉取最新代码 +
 core:(102.0.10+gf249b2e+chromium-102.0.5005.115\107.1.9+g1f0a21a+chromium-107.0.5304.110\110.0.26+g732747f+chromium-110.0.5481.97)
2. ./generate-mac-arm64.sh 生成 xcdoe 工程
3. 打开 xcode 工程，运行 QCefViewTest
4. 报错

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
正常运行无报错，正常相应鼠标滚轮

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)

![QQ截图20230914151830](https://github.com/CefView/QCefView/assets/109504075/ea725b92-5a29-4d40-94d9-a187df26db64)

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode: 都试了
 - OS & Version: macos 13.5 arm64 m2
 - Qt Version: 6.2.4 
 - CEF Version:1.0.8 + 102.0.10+gf249b2e+chromium-102.0.5005.115_macosarm64
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
110.0.26+g732747f+chromium-110.0.5481.97

**Comment by tishion** [comment]
main.cpp里面增加如下：

```cpp
  // set cache path
  config.setCachePath(QDir::tempPath());
```

CEF自己的bug，mac平台debug模式下，cachepath不设置会触发assert

另外 macOS的NCW模式现在还没有修好。

**Comment by LiYaLinIsLaoSix** [comment]
鼠标滚轮事件需要我自己处理，比如模拟键盘输入？
