### ISSUE TITLE
[FEATURE]初始化设置问题

### ISSUE THREAD

**Issue by Frannncisss** [CefView/QCefView#318]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rendered by markdown, so there's no need to delete them)

** Feature Description 【特性详细描述】**

[//]: # (请在下面描述所需新特性的详细信息)
[//]: # (Please describe the detailed information about the request feature)
请问使用QCefView创建窗口时初始化中可以设置flags吗，比如，我想要设置chrome://flags中的
[unsafely-treat-insecure-origin-as-secure](chrome://flags/#unsafely-treat-insecure-origin-as-secure)配置，如何实现呢？

**Comment by tishion** [comment]
public void [addCommandLineSwitch](https://cefview.github.io/QCefView/zh/docs/reference/QCefConfig#class_q_cef_config_1a2873f9e8e8997db4060348418df16632)(const QString & smitch)

public void [addCommandLineSwitchWithValue](https://cefview.github.io/QCefView/zh/docs/reference/QCefConfig#class_q_cef_config_1a141daa8b02526d190e462cbcb38dbab5)(const QString & smitch, const QString & v)
