### ISSUE TITLE
[BUG]: mac cefview 虚函数onNewPopup不被调用

### ISSUE THREAD

**Issue by LiYaLinIsLaoSix** [CefView/QCefView#319]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 
1、Widget 继承 QCefView，点击页面超级链接，虚函数onNewPopup不会被调用（之前102 重写的onBeforePopup会正常被调用，但是最新版改为onNewPopup不会被调用）；

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
...

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
一、虚函数onNewPopup不会被调用；
    1、Widget 继承 QCefView，实现onNewPopup；
    2、运行app正常显示页面；
    3、点击页面超级链接；
    3、onNewPopup不会被调用，直接新页面；

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
一、继承QCefView，打开新页面虚函数onNewPopup被调用；

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode: 都试了
 - OS & Version: [e.g. Windows/macOS/Linux]  mac arm64 m2  os 13.5
 - Qt Version:Qt 6.2.4
 - CEF Version: cefview-main 最新代码，core  113.3.1+g525fa10+chromium-113.0.5672.128
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by L-Super** [comment]
可使用`onNewBrowser`尝试看看

**Comment by LiYaLinIsLaoSix** [comment]
我不想创建新的窗口，直接调整到该连接

**Comment by LiYaLinIsLaoSix** [comment]
onNewBrowser 是可以实现我的功能，谢谢
