### ISSUE TITLE
[FEATURE] SetPreference 怎么设置网络代理？

### ISSUE THREAD

**Issue by LiYaLinIsLaoSix** [CefView/QCefView#326]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rendered by markdown, so there's no need to delete them)

** Feature Description 【特性详细描述】**
在项目中我需要设置网页代理，但是没有看到示例和网上信息，只看到一些关于cef设置方法。

[//]: # (请在下面描述所需新特性的详细信息)
[//]: # (Please describe the detailed information about the request feature)
我在网上看到
CefRefPtr<CefDictionaryValue> dict = CefDictionaryValue::Create();
dict->SetString("mode", "fixed_servers");
dict->SetString("server", "192.168.1.100:8000");

CefRefPtr<CefValue> value = CefValue::Create();
value->SetDictionary(dict);
context->SetPreference("proxy", value, error);

我需要怎么通过QCefView 里的方法设置网页代理？

**Comment by StackExplode** [comment]
`config.addCommandLineSwitchWithValue("--proxy-server","http://127.0.0.1:1081");`

**Comment by tishion** [comment]
```cpp
  QJsonObject proxy{
    { "mode", "fixed_servers" },        //
    { "server", "192.168.1.100:8000" }, //
  };
  QString error;
  qcefview->setPreference("proxy", QVariant(proxy), error);
```
