### ISSUE TITLE
[FEATURE] 支持 qt6.52 ?

### ISSUE THREAD

**Issue by icyfox168168** [CefView/QCefView#331]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rendered by markdown, so there's no need to delete them)

** Feature Description 【特性详细描述】**

[//]: # (请在下面描述所需新特性的详细信息)
[//]: # (Please describe the detailed information about the request feature)
...

**Comment by L-Super** [comment]
支持
