### ISSUE TITLE
qml usage

### ISSUE THREAD

**Issue by sancelot** [CefView/QCefView#34]
Hi,
Is there a way to use it as a qml component ?
Regards,
Steph

**Comment by tishion** [comment]
hi @sancelot, this is in the roadmap, but I need to investigate the feasibility, I am creating a requirement to implement this.

**Comment by tishion** [comment]
and welcome contribution if you have been on the road already.

**Comment by tishion** [comment]
Since QCefView has supported CEF OSR mode, it is more like a normal QWidget now. I believe you can integrate it with QML like other QWidget successfully. I am closing this issue now.

**Comment by tishion** [comment]
Since QCefView has supported CEF OSR mode, it is more like a normal QWidget now. I believe you can integrate it with QML like other QWidget successfully. I am closing this issue now.
