### ISSUE TITLE
您好，Linux环境下Qt生成的QCefViewTest不能执行

### ISSUE THREAD

**Issue by ZhaoSZun** [CefView/QCefView#35]
Linux下cmake生成的QCefViewTest使用命令可执行成功。但是使用qmake -project 生成的项目在Qt 中运行，生成的QCefViewTest使用./QCefViewTest 执行后失败，终端显示到  QFactoryLoader::QFactoryLoader() checking directory path "/home/zhaosz/work/library/QCefView/example/build-QCefViewTest-Desktop_Qt_5_12_10_GCC_64bit-Debug/styles" ...  卡着不动了。debug 项目时执行到main函数中的  QCefContext cefContext(&a, &config); 卡着不动。

![image](https://user-images.githubusercontent.com/36222904/153564721-16b27ac6-cfc4-4402-a628-60a34bd6a397.png)

**Comment by ZhaoSZun** [comment]
> 
是的，./generate-linux-proj.sh -b 编译构建了QCefView，然后用qmake 直接构建了QCefViewTest 这个demo，引用了QCefView生成的动态库，使用Qt Creator调试时不能执行成功，执行到main函数中的 QCefContext cefContext(&a, &config); 卡着不动。

**Comment by tishion** [comment]
cef相关的文件都需要拷贝到可执行程序的同目录

**Comment by ZhaoSZun** [comment]
> cef相关的文件都需要拷贝到可执行程序的同目录

拷贝了，把动态库都开进来了。不报错不好定位原因
![image](https://user-images.githubusercontent.com/36222904/153703148-948ee9eb-c541-41d8-bcf5-85aa89e68db9.png)

**Comment by ZhaoSZun** [comment]
已找到原因，要先加载libcef.so
      # On linux platform and debug mode, libcef.so MUST be loaded before libc.so.
      # Gnerally we can achive this by using LD_PRELOAD=libcef.so, but this is not 
      # convenience for debugging. 
      # Thus, here we do a trick to make sure the load order

**Comment by tishion** [comment]
请帮忙关闭issue，谢谢
