### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by 1005490940** [CefView/QCefView#353]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rendered by markdown, so there's no need to delete them)

** Feature Description 【特性详细描述】**
我想修改QCefView的源码，并在我们的商业项目里面引用QCefView。不知道如何联系作者呢？

**Comment by tishion** [comment]
email：sheentianshen#gmail.com  替换#为@
