### ISSUE TITLE
打印预览功能相关设置

### ISSUE THREAD

**Issue by xionghailong1205** [CefView/QCefView#354]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rendered by markdown, so there's no need to delete them)

** Feature Description 【特性详细描述】**

[//]: # (请在下面描述所需新特性的详细信息)
[//]: # (Please describe the detailed information about the request feature)
...

**Comment by xionghailong1205** [comment]
我已经 发现解决方案 是否有人有兴趣了解我的解决方案

**Comment by xionghailong1205** [comment]
> > 我已经 发现解决方案 是否有人有兴趣了解我的解决方案
> 
> 1
目前封装提供的 api 中没有 能有效设置 启动时命令行的方法 
但是 我看了 cef 的官方文档 并且自己尝试了
我在 CEF 中实现了 CefApp::OnBeforeCommandLineProcessing()
这个 虚函数 在这里添加 命令行参数之后能实现打印预览 不知道是否是我 使用的的有问题。
目前代码库中有方法直接 添加 启动命令行吗
如果没有的话 我的解决方案就是 在cef 源代码中 实现这个虚函数之后重新编译 
这个命令行影响还是很大的 比如设置主语言为中文 开启打印预览

**Comment by L-Super** [comment]
> > > 我已经 发现解决方案 是否有人有兴趣了解我的解决方案
> > 
> > 1
> 目前封装提供的 api 中没有 能有效设置 启动时命令行的方法 
> 但是 我看了 cef 的官方文档 并且自己尝试了
> 我在 CEF 中实现了 CefApp::OnBeforeCommandLineProcessing()
> 这个 虚函数 在这里添加 命令行参数之后能实现打印预览 不知道是否是我 使用的的有问题。
> 目前代码库中有方法直接 添加 启动命令行吗
> 如果没有的话 我的解决方案就是 在cef 源代码中 实现这个虚函数之后重新编译 
> 这个命令行影响还是很大的 比如设置主语言为中文 开启打印预览
> 

https://cefview.github.io/QCefView/docs/reference/QCefConfig#class_q_cef_config_1a2873f9e8e8997db4060348418df16632

QCefConfig 添加命令行参数的方式不行吗？

**Comment by xionghailong1205** [comment]
> > > > 我已经 发现解决方案 是否有人有兴趣了解我的解决方案
> > > 
> > > 
> > > 1
> > > 目前封装提供的 api 中没有 能有效设置 启动时命令行的方法
> > > 但是 我看了 cef 的官方文档 并且自己尝试了
> > > 我在 CEF 中实现了 CefApp::OnBeforeCommandLineProcessing()
> > > 这个 虚函数 在这里添加 命令行参数之后能实现打印预览 不知道是否是我 使用的的有问题。
> > > 目前代码库中有方法直接 添加 启动命令行吗
> > > 如果没有的话 我的解决方案就是 在cef 源代码中 实现这个虚函数之后重新编译
> > > 这个命令行影响还是很大的 比如设置主语言为中文 开启打印预览
> 
> https://cefview.github.io/QCefView/docs/reference/QCefConfig#class_q_cef_config_1a2873f9e8e8997db4060348418df16632
> 
> QCefConfig 添加命令行参数的方式不行吗？

不行的 cef 中也不行 只有 在 我说的那个虚函数中 实现

**Comment by L-Super** [comment]
> > > > > 我已经 发现解决方案 是否有人有兴趣了解我的解决方案
> > > > 
> > > > 
> > > > 1
> > > > 目前封装提供的 api 中没有 能有效设置 启动时命令行的方法
> > > > 但是 我看了 cef 的官方文档 并且自己尝试了
> > > > 我在 CEF 中实现了 CefApp::OnBeforeCommandLineProcessing()
> > > > 这个 虚函数 在这里添加 命令行参数之后能实现打印预览 不知道是否是我 使用的的有问题。
> > > > 目前代码库中有方法直接 添加 启动命令行吗
> > > > 如果没有的话 我的解决方案就是 在cef 源代码中 实现这个虚函数之后重新编译
> > > > 这个命令行影响还是很大的 比如设置主语言为中文 开启打印预览
> > 
> > 
> > https://cefview.github.io/QCefView/docs/reference/QCefConfig#class_q_cef_config_1a2873f9e8e8997db4060348418df16632
> > QCefConfig 添加命令行参数的方式不行吗？
> 
> 不行的 cef 中也不行 只有 在 我说的那个虚函数中 实现

简单看了一下源码，QCefConfig应该是通过`OnBeforeCommandLineProcessing()`添加的参数

![image](https://github.com/CefView/QCefView/assets/40905056/aa29d14a-1667-426f-83f3-de057388eee0)

**Comment by L-Super** [comment]
我通过在main.cpp添加参数实现了打印预览：
```cpp
config.addCommandLineSwitch("--enable-print-preview");
```
![image](https://github.com/CefView/QCefView/assets/40905056/df655aef-198c-487c-b877-f945612b7187)

**Comment by xionghailong1205** [comment]
> 我通过在main.cpp添加参数实现了打印预览：
> 
> ```c++
> config.addCommandLineSwitch("--enable-print-preview");
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/40905056/291463300-df655aef-198c-487c-b877-f945612b7187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTgxMjQsIm5iZiI6MTcwMjk1NzgyNCwicGF0aCI6Ii80MDkwNTA1Ni8yOTE0NjMzMDAtZGY2NTVhZWYtMTk4Yy00ODdjLWI4NzctZjk0NTYxMmI3MTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAzNTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OGRlZmUzYjM1ZTJjNTEwY2ZkZWFiYTE2MWNmMGYyZGNlNDM0ZDQ1OTc4NjdlYjM5ZDcyMDc0M2NiZmNlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PJRFUWvQQ2sy-ArYfkQQqs2QSpoVcttzPbEeG99Fmtg)

这可能类似于 父进程 传递命令行参数到子进程启动项中了 谢谢你的解决方案

**Comment by xionghailong1205** [comment]
> 我通过在main.cpp添加参数实现了打印预览：
> 
> ```c++
> config.addCommandLineSwitch("--enable-print-preview");
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/40905056/291463300-df655aef-198c-487c-b877-f945612b7187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzcwNTgsIm5iZiI6MTcwMjk3Njc1OCwicGF0aCI6Ii80MDkwNTA1Ni8yOTE0NjMzMDAtZGY2NTVhZWYtMTk4Yy00ODdjLWI4NzctZjk0NTYxMmI3MTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA5MDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMzEzMjMyNzNkZGFiNTQ3NDU5ZTQ0NDg3NzdlZDAzMmIyN2QwNWUzMmFiNzA2YzFmM2Q5YmY1Y2QxZjE3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._mZTmFZwqQlyZ-oHl-FV9iL9e0fEJHjCmMhk_QvqF2Q)

我设置 但是没有效果

**Comment by L-Super** [comment]
QCefViewTest:
```cpp
config.setWindowlessRenderingEnabled(false);
config.addCommandLineSwitch("--enable-print-preview");
```
需要设置为NCW模式，如果是OSR，会弹出旧式打印对话框，没有打印预览功能。
测试平台：Windows 11

![image](https://github.com/CefView/QCefView/assets/40905056/4b9a6ddb-942b-477f-9323-0b1525eb26b1)
