### ISSUE TITLE
[BUG]:  在外接显示器的时候 无法在副屏正常显示

### ISSUE THREAD

**Issue by xionghailong1205** [CefView/QCefView#362]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
...

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)

**Expected behavior 【正确的预期行为】**

[//]: # (在下面填写如果不存在该BUG时候预期的正确行为)
[//]: # (A clear and concise description of what you expected to happen)
...

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode:
 - OS & Version: [e.g. Windows/macOS/Linux]
 - Qt Version:
 - CEF Version:
 

**Additional context 【更多额外信息】**

[//]: # (如有更多额外信息，请在下面添加)
[//]: # (Add any other context about the problem here)
...

**Comment by zhouFear** [comment]
我也遇到了同样的问题，![image](https://github.com/CefView/QCefView/assets/13234521/8549b135-ca1e-4eed-ba70-855c71ce2b36) 
![image](https://github.com/CefView/QCefView/assets/13234521/1483c947-fdae-4d8c-9d3d-acc1c52d046a)
主屏幕是1920*1080,100%缩放，副屏是4k，150%缩放， 打开QCefviewTest在主屏幕上显示正常，拖动到副屏时显示不正常 
![image](https://github.com/CefView/QCefView/assets/13234521/609e5a0c-15f9-4452-a59f-329a2fc9c63a)

**Comment by zhouFear** [comment]
NCW Mode

**Comment by xionghailong1205** [comment]
> NCW Mode

和显示器分辩率有关系,如果两个显示器分辩相同就没问题,貌似

**Comment by L-Super** [comment]
Qt版本是多少 @zhouFear @xionghailong1205

**Comment by zhouFear** [comment]
Qt 5.15.2

**Comment by xionghailong1205** [comment]
> Qt版本是多少 @zhouFear @xionghailong1205 

有啥进展吗

**Comment by L-Super** [comment]
提供的信息有限，无法排查。另，未复现

**Comment by tishion** [comment]
会修复
