### ISSUE TITLE
Qt端向JS端传递消息 方式优化

### ISSUE THREAD

**Issue by zlozl233** [CefView/QCefView#41]
Qt端向JS端传递消息，有如下函数功能没有？直接执行JS回调
void WBWebViewComponent::CallBackToJs(const QString &function, const QString &arguments)
{
    CefRefPtr<CefFrame> frame =GetBrowser(m_browserHandlerIndex)->GetMainFrame();
    QString datastr = QString("%1('").arg(function);
    datastr += arguments;
    datastr += "')";
    CefString code;
    //code.FromString(std::string(datastr.toLocal8Bit().data()));
    code.FromString(datastr.toStdString());
    frame->ExecuteJavaScript(code, frame->GetURL(), 0);
}

**Comment by tishion** [comment]
WIP
