### ISSUE TITLE
[BUG]: CMake脚本生成了sln，但是其中的“生成后事件”中的脚本代码与“链接器-清单文件-UAC执行级别”冲突

### ISSUE THREAD

**Issue by SwartzBushnell** [CefView/QCefView#412]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Describe the bug 【Bug描述】** 
具体而言，表现为编译失败，且报错
'Values of attribute 'level' not equal in different manifest snippets'

[//]: # (在下面填写描述BUG发生的表现)
[//]: # (A clear and concise description of what the bug is)
...

**To Reproduce 【复现步骤】**

[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. Go to '项目属性-链接器-清单文件'
2. 将"UAC执行级别"从默认的“asInvoker (/level='asInvoker')”调整为requireAdministrator (/level='requireAdministrator')
3. 确定后执行编译

**Expected behavior 【正确的预期行为】**
应当允许编译

**Screenshots 【截图】**

[//]: # (如果可以请在下面请提供BUG的截图信息)
[//]: # (If applicable, add screenshots to help explain your problem)
...

**Environment 【BUG产生的环境】**

[//]: # (请提供以下信息，OSR和非OSR模式为必须提供项目，无此项目issue不会被处理)
[//]: # (Please complete the following information, OSR/NCW is mandatory)
 - OSR/NCW Mode: 任意
 - OS & Version: [e.g. Windows/macOS/Linux]  win10，vs2019 社区版 v16.11.36 && v16.11.37
 - Qt Version: 5.12
 - CEF Version: 109.1.16+g454cbc2+chromium-109.0.5414.87

**Additional context 【更多额外信息】**
若要编译成功，需要在“生成后事件”中删除脚本代码

**Comment by tishion** [comment]
你是自己手动改了level吧，QCefView内的任何项目都不会调整invoke level

**Comment by SwartzBushnell** [comment]
是的我调整了。从结果来说，脚本代码没有给到我admin level，因此我只能手动调整level。
