### ISSUE TITLE
[BUG]:  MP4预览右下角按钮为英文，而chrome中是中文

### ISSUE THREAD

**Issue by linshangqiang** [CefView/QCefView#420]
## mp4播放时，chrome右下角按钮正常且是中文，使用cef播放，右下角按钮只有两个，少了画中画，且是英文
![image](https://github.com/CefView/QCefView/assets/74175499/e019d651-f100-40ff-814d-9debcde065f0)
![image](https://github.com/CefView/QCefView/assets/74175499/06eedbc7-8eba-4088-b3ae-79764eaf4558)
![image](https://github.com/CefView/QCefView/assets/74175499/768fcfdb-534d-48cc-ac7f-f4269f509c2b)

以上问题有解决方法吗，可以不要有画中画，但按钮需要中文显示。

...

**Comment by linshangqiang** [comment]
视频截图画面有误，补充一张chrome中播放同个视频的截图
![image](https://github.com/CefView/QCefView/assets/74175499/8685b6ac-784e-4732-a4fa-accd24b8bcf1)

**Comment by linshangqiang** [comment]
关于QCefView如何支持播放视频：https://blog.csdn.net/whjy_lsq/article/details/140158447

**Comment by linshangqiang** [comment]
![image](https://github.com/CefView/QCefView/assets/74175499/b041152c-2f19-47f6-851e-5cba7f4f4128)

跟菜单有关系，右键页面也是英文，如何更改成中文呢？

**Comment by L-Super** [comment]
显示为英文，大概率是没有设置区域，参考[setLocale](https://cefview.github.io/QCefView/zh/docs/reference/QCefConfig#class_q_cef_config_1af67e837996a1dd84af0866f76588ba4e)

**Comment by linshangqiang** [comment]
> 显示为英文，大概率是没有设置区域，参考[setLocale](https://cefview.github.io/QCefView/zh/docs/reference/QCefConfig#class_q_cef_config_1af67e837996a1dd84af0866f76588ba4e)

感谢回复，已解决，加入 config.setLocale("zh-CN");即可。可关闭
