### ISSUE TITLE
请问是否考虑支持JS的异步返回

### ISSUE THREAD

**Issue by bernardx** [CefView/QCefView#43]
目前js和c++的交互是单向的，虽然可以定义接口，但比较麻烦。
是否可以考虑加入一个统一的异步返回
CefSharp的相关实现： (https://github.com/cefsharp/CefSharp/blob/7f870db945db29c447555724d200fed281791f6e/CefSharp.Core.Runtime/Internals/CefFrameWrapper.cpp#L229)

**Comment by tishion** [comment]
QCefQuery可以异步返回结果
https://cefview.github.io/QCefView/zh/docs/guide/CefviewQuery

executeJavascript的方法暂时不会支持添加返回结果，不过欢迎你提交PR

**Comment by bernardx** [comment]
OK 我看下哪种实现比较好
