### ISSUE TITLE
请问如何添加F12 Debug窗口？

### ISSUE THREAD

**Issue by xuchendev** [CefView/QCefView#44]
看到网上有CEF原生API如何添加F12 Debug窗口的文章，请问QCefView这边要如何添加呢？

**Comment by tishion** [comment]
https://bitbucket.org/chromiumembedded/cef/src/a2c621bf8b7cc323138c795b8a90629a8d35334c/include/cef_browser.h#lines-513

QCefView暂时不暴露这个接口。
