### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by tianzuoz** [CefView/QCefView#445]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rendered by markdown, so there's no need to delete them)

** Feature Description 【特性详细描述】**
QCefContext 可以和QApp 不一样的lifecycle么？需要的时候起来ok不？

[//]: # (请在下面描述所需新特性的详细信息)
[//]: # (Please describe the detailed information about the request feature)
...

` 
 // create QCefContext instance with config,
  // the lifecycle of cefContext must be the same as QApplication instance
  QCefContext cefContext(&a, argc, argv, &config);

`

我在我的QT项目里面想使用QCefView，现在就是要在main函数里面，创建这个QCefContext，有没有办法在需要的时候再做？

谢谢啦！

**Comment by tishion** [comment]
我估计不行，你可以自己改改试试。
QT的生命周期管理稍微复杂点，为了屏蔽这一点，所以设计的时候就没有考虑可动态反初始化了。另外CEF能不能在进程结束前安全的反初始化我也不确定。
所以你可以自己改改试试。
