### ISSUE TITLE
[BUG]: vs2022，Qt5.14.2, 编译32位的QCefView， 试图实验下载功能，点击demo右侧的那些下载按钮后程序崩溃

### ISSUE THREAD

**Issue by allenhiman** [CefView/QCefView#454]
[//]: # (以下所有的以"[//]: #"开始的文字都是注释，不会被markdown渲染，所以无需删除)
[//]: # (All lines start "with [//]: #" below are comment lines and will not be rebdered by markdown, so there's no need to delete them)

[//]: # (注意：如果你发现的BUG是由于使用了与当前代码库中不同的Qt/CEF版本，该BUG将会被忽略)
[//]: # (Node: if you find some bugs caused by using different CEF/Qt version with the one in current repo, this report will be ignored)

**Release 32位运行demo 点击右侧网页的“50M”那个小按钮，程序崩溃，崩溃堆栈在libCef里面，但看不到具体的情况. (必现）** 
请问这可能是什么原因导致的？

**点击任意一个下载按钮都崩溃**

![image](https://github.com/user-attachments/assets/85defc56-c65c-4fc2-9a9e-b35e47879ae9)

![image](https://github.com/user-attachments/assets/af96afe8-7715-4c0f-a9a4-42f55c195d57)

**Comment by ckJust** [comment]
![image](https://github.com/user-attachments/assets/0da57823-c904-4792-a0b7-120a78dd7416)
我也遇到这个问题

**Comment by tishion** [comment]
相关逻辑没有改动，换一下CEF版本试试吧，最新的都没有测试那么全面。

**Comment by tishion** [comment]
Fixed
QCefView: https://github.com/CefView/QCefView/commit/398edab4ae011ff4c59644eb10c0c6b2d2542f33

CefViewCore: https://github.com/CefView/CefViewCore/commit/a6a6d62fd5783297ed0d3ffb8379dec4f2ea1143
