### ISSUE TITLE
[BUG]: 文件打开对话框如何阻塞页面操作？

### ISSUE THREAD

**Issue by lxylbds** [CefView/QCefView#457]
[//]: # (在下面填写复现该BUG的详细操作步骤)
[//]: # (Steps to reproduce the behavior)
1. 页面内点击按钮调用input file打开这件先择框。
2. 此时页面并未阻塞操作，仍可重复点击上一步的按钮。
3. 文件框中选择文件，点击确定，关闭文件框，此时文件框再次弹出
4. 这导致两个问题，web只能获取到第二次文件框选择的文件，第一次的获取不到。
5. 观察chrome中，重复上述步骤时，第一次点击按钮后页面进入阻塞状态，无法再次点击。

是否可以通过什么配置解决以上问题？
如果没有，qt如何能感知到文件框的打开和关闭？

**Comment by tishion** [comment]
3a1bd3c373448c58f87b67c13ae7eb2c9eeb428c
