### ISSUE TITLE
配置日志输出重定向输出指定文件

### ISSUE THREAD

**Issue by huiseliming** [CefView/QCefView#46]
配置日志输出重定向输出指定文件，不输出给std::cout

**Comment by tishion** [comment]
QCefView本身没有log（用于调试的log都是通过qDebug()输出）。
QCefViewCore的log目前只输出到各个平台的默认log系统，macOS和Linux到syslog，Windows到DebugStringBuffer，这部分不会提供输出到文件的功能，因为QCefViewCore只是一个组件，而log文件是使用了该组件的产品才需要的。

没有任何log会输出到std::out

**Comment by huiseliming** [comment]
我在windows下运行，日志在ConsoleWindow里不断打印

**Comment by huiseliming** [comment]
我在windows下运行，日志在ConsoleWindow里不断打印
是不是重定向输出日志到了std::cout
问下这些日志时cef打印的还是QcefView打印的

**Comment by huiseliming** [comment]
类似这种日志，他是由cef生成的还是QcefView生成的
[0223/172636.643:VERBOSE1:node_controller.cc(150)] Initializing node 1504493AB52288F4.4C8E88536DEBF558
[0223/172636.644:INFO:content_main_runner_impl.cc(1065)] Chrome is running in full browser mode.
[0223/172636.661:VERBOSE1:pref_proxy_config_tracker_impl.cc(186)] 0000053674DD0610: set chrome proxy config service to 0000053674DE1E10
[0223/172636.680:VERBOSE1:webrtc_internals.cc(118)] Could not get the download directory.
[0223/172636.681:VERBOSE1:media_stream_manager.cc(700)] MSM::InitializeMaybeAsync([this=0000053674E302D0])
[0223/172636.681:VERBOSE1:media_stream_manager.cc(700)] MDM::MediaDevicesManager()
[0223/172636.681:VERBOSE1:media_stream_manager.cc(700)] MSM::MediaStreamManager([this=0000053674E302D0]))

DevTools listening on ws://127.0.0.1:9000/devtools/browser/c3f4725c-7837-4a40-b319-544782e17082
[0223/172636.796:VERBOSE1:node_controller.cc(847)] Node 1504493AB52288F4.4C8E88536DEBF558 accepted invitee AEC7F1538BD753D8.1B9A703FE259BAFC
[0223/172636.797:VERBOSE1:node.cc(466)] Sending MergePort from 20C058BA39239213.9A731A4ED4ECC916@1504493AB52288F4.4C8E88536DEBF558 to F89D23F631F4D27A.B8F1FE394FDFEAF8@AEC7F1538BD753D8.1B9A703FE259BAFC
[0223/172636.797:VERBOSE1:node.cc(466)] Sending MergePort from CD6DDC25A3EB8D37.964DA56B45104A0C@1504493AB52288F4.4C8E88536DEBF558 to 9AF4BA1F2FE1B5D.269C3FC06267C74E@AEC7F1538BD753D8.1B9A703FE259BAFC
[0223/172637.026:VERBOSE1:node_controller.cc(847)] Node 1504493AB52288F4.4C8E88536DEBF558 accepted invitee BFF1896667123669.E24C3E80E3739736
[0223/172637.026:VERBOSE1:node.cc(466)] Sending MergePort from 30D5B69412446421.6CEA39767371622@1504493AB52288F4.4C8E88536DEBF558 to 322BDA18069071D3.D3FD2CD3B9AAE154@BFF1896667123669.E24C3E80E3739736
[0223/172637.031:VERBOSE1:node.cc(466)] Sending MergePort from F37AC8BBC3D65F7E.A5A24DBA309F8E01@1504493AB52288F4.4C8E88536DEBF558 to 90C2CFBCDB76E8C9.4EF22AB07FE999EA@BFF1896667123669.E24C3E80E3739736
[0223/172638.384:VERBOSE1:node_controller.cc(604)] Dropped peer BFF1896667123669.E24C3E80E3739736
[0223/172638.384:VERBOSE1:node.cc(503)] Observing lost connection from node 1504493AB52288F4.4C8E88536DEBF558 to node BFF1896667123669.E24C3E80E3739736
[0223/172638.386:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: BFF1896667123669.E24C3E80E3739736
[0223/172638.386:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: BFF1896667123669.E24C3E80E3739736
[0223/172638.387:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: BFF1896667123669.E24C3E80E3739736
[0223/172638.387:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: BFF1896667123669.E24C3E80E3739736
[0223/172638.387:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: BFF1896667123669.E24C3E80E3739736
[0223/172638.387:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: BFF1896667123669.E24C3E80E3739736
[0223/172638.388:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: BFF1896667123669.E24C3E80E3739736
[0223/172638.395:VERBOSE1:histogram.cc(444)] Histogram: Media.VideoCaptureService.DurationFromLastConnectToClosingConnectionAfterEnumerationOnly has bad minimum: 0
[0223/172638.539:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: BFF1896667123669.E24C3E80E3739736
[0223/172638.541:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: AEC7F1538BD753D8.1B9A703FE259BAFC
[0223/172638.580:VERBOSE1:statistics_recorder.cc(430)] Collections of all histograms
Histogram: ChildProcess.Disconnected2 recorded 1 samples, mean = 6.0 (flags = 0x1)
0  ...
6  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
7  ...

Histogram: ContentSettings.DefaultAutoplaySetting recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ...

Histogram: ContentSettings.DefaultCookiesSetting recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ...

Histogram: ContentSettings.DefaultIdleDetectionSetting recorded 1 samples, mean = 3.0 (flags = 0x1)
0  ...
3  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
4  ...

Histogram: ContentSettings.DefaultImagesSetting recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ...

Histogram: ContentSettings.DefaultJavaScriptSetting recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ...

Histogram: ContentSettings.DefaultLocationSetting recorded 1 samples, mean = 3.0 (flags = 0x1)
0  ...
3  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
4  ...

Histogram: ContentSettings.DefaultMIDISysExSetting recorded 1 samples, mean = 3.0 (flags = 0x1)
0  ...
3  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
4  ...

Histogram: ContentSettings.DefaultMediaStreamCameraSetting recorded 1 samples, mean = 3.0 (flags = 0x1)
0  ...
3  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
4  ...

Histogram: ContentSettings.DefaultMediaStreamMicSetting recorded 1 samples, mean = 3.0 (flags = 0x1)
0  ...
3  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
4  ...

Histogram: ContentSettings.DefaultNotificationsSetting recorded 1 samples, mean = 3.0 (flags = 0x1)
0  ...
3  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
4  ...

Histogram: ContentSettings.DefaultPopupsSetting recorded 1 samples, mean = 2.0 (flags = 0x1)
0  ...
2  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
3  ...

Histogram: ContentSettings.DefaultSoundSetting recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ...

Histogram: ContentSettings.DefaultSubresourceFilterSetting recorded 1 samples, mean = 2.0 (flags = 0x1)
0  ...
2  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
3  ...

Histogram: ContentSettings.DefaultUsbGuardSetting recorded 1 samples, mean = 3.0 (flags = 0x1)
0  ...
3  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
4  ...

Histogram: ContentSettings.DefaultWebBluetoothGuardSetting recorded 1 samples, mean = 3.0 (flags = 0x1)
0  ...
3  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
4  ...

Histogram: ContentSettings.Exceptions.accessibility-events recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.app-banner recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.ar recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.auto-select-certificate recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.automatic-downloads recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.autoplay recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.background-sync recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.bluetooth-chooser-data recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.bluetooth-guard recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.bluetooth-scanning recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.camera-pan-tilt-zoom recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.client-hints recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.clipboard recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.cookies recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.cookies.Allow recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.cookies.AllowThirdParty recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.cookies.Block recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.cookies.SessionOnly recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.durable-storage recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.file-system-last-picked-directory recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.file-system-read-guard recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.file-system-write-guard recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.font-access recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.geolocation recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.hid-chooser-data recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.hid-guard recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.idle-detection recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.images recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.important-site-info recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.insecure-private-network recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.installed-web-app-metadata recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.intent-picker-auto-display recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.javascript recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.legacy-cookie-access recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.media-engagement recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.media-stream-camera recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.media-stream-mic recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.midi-sysex recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.mixed-script recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.nfc recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.notifications recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.password-protection recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.payment-handler recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.permission-autoblocking-data recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.permission-autorevocation-data recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.popups recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.popups.Allow recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.popups.Block recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.ppapi-broker recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.protocol-handler recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.safe-browsing-url-check-data recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.sensors recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.serial-chooser-data recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.serial-guard recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.site-engagement recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.sound recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.ssl-cert-decisions recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.storage-access recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.subresource-filter recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.subresource-filter-data recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.subresource-filter.Allow recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.subresource-filter.Block recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.usb-chooser-data recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.usb-guard recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.vr recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.Exceptions.window-placement recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: ContentSettings.NumberOfExceptions recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: DirectWrite.Fonts.Gfx.InitializeLoopCount recorded 1 samples (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)

Histogram: Enterprise.PolicyLoadStatus recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ...

Histogram: EnterpriseCheck.InDomain recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: EnterpriseCheck.IsDomainJoined recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: EnterpriseCheck.IsEnterpriseUser recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: EnterpriseCheck.IsLocalMachine recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: EnterpriseCheck.IsLocalUser recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: EnterpriseCheck.IsManaged2 recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: EnterpriseCheck.NetGetJoinInformationAddress recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: EnterpriseCheck.OSType recorded 1 samples, mean = 3.0 (flags = 0x1)
0  ...
3  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
4  ...

Histogram: GPU.BlocklistFeatureTestResults.Accelerated2dCanvas recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: GPU.BlocklistFeatureTestResults.GpuCompositing recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: GPU.BlocklistFeatureTestResults.GpuRasterization recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: GPU.BlocklistFeatureTestResults.OopRasterization recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: GPU.BlocklistFeatureTestResults.Webgl recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: GPU.BlocklistFeatureTestResults.Webgl2 recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: GPU.BlocklistTestResultsPerEntry recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: GPU.DriverBugTestResultsPerEntry recorded 11 samples (flags = 0x1)
0    ------------------------------------------------------------------------O (1 = 9.1%)
17   ------------------------------------------------------------------------O (1 = 9.1%)
54   ------------------------------------------------------------------------O (1 = 9.1%)
88   ------------------------------------------------------------------------O (1 = 9.1%)
132  ------------------------------------------------------------------------O (1 = 9.1%)
206  ------------------------------------------------------------------------O (1 = 9.1%)
207  ------------------------------------------------------------------------O (1 = 9.1%)
345  ------------------------------------------------------------------------O (1 = 9.1%)
347  ------------------------------------------------------------------------O (1 = 9.1%)
360  ------------------------------------------------------------------------O (1 = 9.1%)
368  ------------------------------------------------------------------------O (1 = 9.1%)

Histogram: GPU.GPUInitializationTime.V3 recorded 1 samples, mean = 113393.0 (flags = 0x1)
0       ...
102673  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
118565  ...

Histogram: GPU.GPUProcessInitialized recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: GPU.GPUProcessLaunchTime recorded 1 samples, mean = 8.0 (flags = 0x1)
0  ...
8  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
10 ...

Histogram: GPU.GPUProcessTerminationStatus2 recorded 1 samples, mean = 4.0 (flags = 0x1)
0  ...
4  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
5  ...

Histogram: GPU.ProcessLifetimeEvents.HardwareAccelerated recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: LibraryLoader.LoadNativeLibraryWindows recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ...

Histogram: MPArch.ChildProcessLaunchFirst recorded 1 samples, mean = 7.0 (flags = 0x1)
0  ...
7  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
8  ...

Histogram: MPArch.ChildProcessLaunchSubsequent recorded 1 samples, mean = 5.0 (flags = 0x1)
0  ...
5  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
6  ...

Histogram: Media.VideoCaptureService.DurationFromLastConnectToClosingConnectionAfterEnumerationOnly recorded 1 samples, mean = 178734832.0 (flags = 0x1)
0      ...
60000  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}

Histogram: Media.VideoCaptureService.Event recorded 1 samples, mean = 7.0 (flags = 0x1)
0  ...
7  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
8  ...

Histogram: Net.DNS.DnsConfig.SecureDnsMode recorded 1 samples, mean = 2.0 (flags = 0x1)
0  ...
2  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
3  ...

Histogram: Net.NotifyAddrChangeFailures recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: NetworkService.TimeToFirstResponse recorded 1 samples, mean = 183.0 (flags = 0x1)
0    ...
171  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
210  ...

Histogram: NetworkService.TimeToFirstResponse.OnStartup recorded 1 samples, mean = 183.0 (flags = 0x1)
0    ...
171  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
210  ...

Histogram: Plugin.FlashUsage recorded 1 samples, mean = 2.0 (flags = 0x1)
0  ...
2  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
3  O                                                                         (0 = 0.0%) {100.0%}

Histogram: SharedMemory.MapBlockedForSecurity recorded 4 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (4 = 100.0%)
1  ...

Histogram: Startup.BrowserMainRunnerImplInitializeLongTime recorded 1 samples, mean = 43.0 (flags = 0x1)
0   ...
43  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
50  ...

Histogram: Startup.BrowserMainRunnerImplInitializeStep1Time recorded 1 samples, mean = 14.0 (flags = 0x1)
0   ...
14  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
17  ...

Histogram: Startup.BrowserMainRunnerImplInitializeStep2Time recorded 1 samples, mean = 28.0 (flags = 0x1)
0   ...
24  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
29  ...

Histogram: ThreadPool.NumTasksBeforeDetach.Browser.Background recorded 0 samples (flags = 0x1)
0 ...

Histogram: ThreadPool.NumTasksBeforeDetach.Browser.Foreground recorded 0 samples (flags = 0x1)
0 ...

Histogram: UI.DeviceScale recorded 1 samples (flags = 0x1)
100  ------------------------------------------------------------------------O (1 = 100.0%)

Histogram: UMA.PersistentAllocator.FieldTrialAllocator.Errors recorded 0 samples (flags = 0x1)

Histogram: UMA.PersistentAllocator.FieldTrialAllocator.UsedPct recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ...

Histogram: V8.Initializer.LoadV8Snapshot.Result recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

Histogram: V8.Initializer.OpenV8File.Result recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ...

**Comment by tishion** [comment]
Cef打印，通过QCefContext调整级别即可。
