### ISSUE TITLE
将QCefView放入dock一直闪烁

### ISSUE THREAD

**Issue by huiseliming** [CefView/QCefView#47]
将QCefView放入ADS::DockWidget中后整个窗口一直闪烁，不能进行任何操作

我注释了QCefViewPrivate 386行恢复正常
  if (now == q) {
    // QCefView got focus, need to move the focus to the browser window
    setFocus(true);
  } else {
    // Bug fix: https://github.com/CefView/QCefView/issues/30
    // When QCefView got focus then click if click some other widgets(for example a QLineEdit),
    // the QCefView will not release the input focus, so we need to watch the focus change event.

    // release the browser window focus status
    setFocus(false);

    // activate the top level window
    // now->activateWindow();   <---------- 这里
  }
这行代码好像导致了一直在丢失焦点。
注释是否有什么影响

**Comment by tishion** [comment]
可以去掉，应该没有影响，这里只是为了保证CEF Window一定不会一致保持activate状态，所以主动activate了一下。

已经去掉。
https://github.com/CefView/QCefView/commit/10dee9d49f21d9e0704bede59346f3a4e4152c15

**Comment by tishion** [comment]
// activate the top level window
// now->activateWindow();   <---------- 这里

这里不可以删除，删除之后引入问题：#51 

闪烁问题需要其他办法解决。

**Comment by tishion** [comment]
Cannot reproduce

**Comment by tishion** [comment]
https://github.com/CefView/QCefView/commit/0f9c9d4579dcaa03d125ae95b50f953e846de789  fixed

**Comment by tishion** [comment]
https://github.com/CefView/QCefView/commit/6a88d3c4440c7daea833742adce4b8d04ddad560
Fixed completely
