### ISSUE TITLE
初始化setLocale为zh-CN生效，但再次setLocale为en-US后不生效，请问如何解决？

### ISSUE THREAD

**Issue by xuchendev** [CefView/QCefView#48]
在Windows平台下先设置为zh-CN
![image](https://user-images.githubusercontent.com/9381771/155703599-51558f08-3a3c-443f-ade2-39e9764193db.png)
然后在Web交互中更改为en-US
![image](https://user-images.githubusercontent.com/9381771/155703690-8a7b3f3d-5dd3-48bc-bde3-494c78b8be6b.png)

**Comment by tishion** [comment]
这个需要暴露一个新接口了
CefRequestContext::SetPreference(const CefString& name, CefRefPtr<CefValue> value, CefString& error))

安排

**Comment by tishion** [comment]
可以使用QCefView.setPreference接口来更改已经初始化过的一些参数。

如果需要修改语言可以这样写：
```cpp
      QString error;
      if (!qcefView->setPreference("intl.accept_languages", "zh-CN", error)) {
          // failed to set preference, show error message with `error`
      }
```

**Comment by tishion** [comment]
不过我觉得你的做法有点问题，你是想做多语言的应用，首先你的应用应该是分Qt原生部分和Webapp部分的，如果要做多语言比较好的模式应该如下实现：
1. Qt原生实现多语言（实现方式根据你自己的应用而定）
2. WebApp也实现多语言（可以通过URL传参数实现）

多语言切换的触发方式可以放在WebApp中，当用户点击WebApp中的切换语言按钮，通过InvokeMethod通知Native，然后再Qt的invokemethod相应中你需要做如下：
1. 根据JS传入的目标语言参数，使Qt原生部分切换为目标语言
2. 根据JS传入的目标语言参数，生成新的URL，然后通过QCefView的重新navigate到新的URL

**Comment by xuchendev** [comment]
> 不过我觉得你的做法有点问题，你是想做多语言的应用，首先你的应用应该是分Qt原生部分和Webapp部分的，如果要做多语言比较好的模式应该如下实现：
> 
> 1. Qt原生实现多语言（实现方式根据你自己的应用而定）
> 2. WebApp也实现多语言（可以通过URL传参数实现）
> 
> 多语言切换的触发方式可以放在WebApp中，当用户点击WebApp中的切换语言按钮，通过InvokeMethod通知Native，然后再Qt的invokemethod相应中你需要做如下：
> 
> 1. 根据JS传入的目标语言参数，使Qt原生部分切换为目标语言
> 2. 根据JS传入的目标语言参数，生成新的URL，然后通过QCefView的重新navigate到新的URL

**Comment by xuchendev** [comment]
> > 不过我觉得你的做法有点问题，你是想做多语言的应用，首先你的应用应该是分Qt原生部分和Webapp部分的，如果要做多语言比较好的模式应该如下实现：
> > 
> > 1. Qt原生实现多语言（实现方式根据你自己的应用而定）
> > 2. WebApp也实现多语言（可以通过URL传参数实现）
> > 
> > 多语言切换的触发方式可以放在WebApp中，当用户点击WebApp中的切换语言按钮，通过InvokeMethod通知Native，然后再Qt的invokemethod相应中你需要做如下：
> > 
> > 1. 根据JS传入的目标语言参数，使Qt原生部分切换为目标语言
> > 2. 根据JS传入的目标语言参数，生成新的URL，然后通过QCefView的重新navigate到新的URL

我们实现的机制类似，但是出现了一个问题，Web人员反馈他那边调用HTTP接口时候已经指定了Accept-Language，但是不生效，怀疑是被CEF进行了覆盖。所以我们想通过SetLocale这种方式来完成Accept-Language请求头更改。

**Comment by xuchendev** [comment]
> ```c++
> intl.accept_languages
> ```

问题得到解决，牛批！
