### ISSUE TITLE
浏览器获取焦点后不放，QT界面无法响应键盘事件

### ISSUE THREAD

**Issue by reghtml** [CefView/QCefView#51]
您好，我发现了一个问题
![图片](https://user-images.githubusercontent.com/15364651/155910608-b7a6aaca-629f-4ce4-9b26-b8b3620bc4ac.png)
如图，我打开一个百度搜索的界面，此时鼠标点击浏览器内的界面，浏览器获取焦点

然后我再点击QT界面的编辑框，此时光标在编辑框内，输入任何内容都无效，

按home 和 end 键，光标不会前后移动，反而是浏览器界面界面在上下移动

应该是键盘事件还被拿捏在cef里边，此时我如果想在界面输入内容，需要先切换到其他软件里，比如
![图片](https://user-images.githubusercontent.com/15364651/155910872-3dc6e5c6-c220-4801-9f1a-c5a9b4cb0b67.png)

然后再回来点点编辑框就能输入内容了
![图片](https://user-images.githubusercontent.com/15364651/155910918-a976564b-db1a-433f-a215-89c1130d42fb.png)

但是如果在浏览器页面中再次进行点击，就又会重现以上的问题。

我的系统是 win10 ,cef 版本用的里边自带的版本。 ， 这个问题有解决办法吗?

我看到有一个类似的issues已关闭，但是我 qcefview 是刚git clone的最新版，似乎并没有解决

**Comment by tishion** [comment]
该问题为修复 #47 问题时候删除了now->activateWindow(); 导致的。
已经恢复了。
