### ISSUE TITLE
CefBrowserHandler::OnBeforePopup

### ISSUE THREAD

**Issue by zlozl233** [CefView/QCefView#53]
bool WBCefBrowserHandler::OnBeforePopup(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame, const CefString &target_url, const CefString &target_frame_name, CefLifeSpanHandler::WindowOpenDisposition target_disposition, bool user_gesture, const CefPopupFeatures &popupFeatures, CefWindowInfo &windowInfo, CefRefPtr<CefClient> &client, CefBrowserSettings &settings, bool *no_javascript_access)
{
    if (m_isNewPopup) {
        //跳转到另外一个窗口打开，此窗口保持不变
        emit onBeforePopupUrl(QString::fromStdString(target_url.ToString()));
        return true;
    }
    switch (target_disposition)
    {
        case WOD_NEW_FOREGROUND_TAB:
        case WOD_NEW_BACKGROUND_TAB:
        case WOD_NEW_POPUP:
        case WOD_NEW_WINDOW: {
            //取消创建并在同一个browser打开
            browser->GetMainFrame()->LoadURL(target_url);
            return true;
        }
    }
    return false;
}

**Comment by zlozl233** [comment]
我希望可以增加一个接口可以实现 打开页面的自定义控制，thinks

**Comment by tishion** [comment]
这个接口暴露有点复杂，我评估一下。

**Comment by tishion** [comment]
Done
