### ISSUE TITLE
mCefView->executeJavascript(QCefView::MainFrameID, callbackString, "") Crash

### ISSUE THREAD

**Issue by zlozl233** [CefView/QCefView#58]
void WBWebViewComponent::runJavaScript(const QString &callbackString)
{
    bool ok = mCefView->executeJavascript(QCefView::MainFrameID, callbackString, "");
    qDebug()<<__FUNCTION__<<ok;
}
is Crash

fix: this Crash
修改代码如下，可解决Carsh
bool QCefViewPrivate::executeJavascript(int64_t frameId, const QString& code, const QString& url)
{
  if (pCefBrowser_) {
    auto frame = frameId == 0 ? pCefBrowser_->GetMainFrame() : pCefBrowser_->GetFrame(frameId);
    //CefRefPtr<CefFrame> frame = pCefBrowser_->GetFrame(frameId);
    if (frame) {
      CefString c;
      c.FromString(code.toStdString());

      CefString u;
      if (url.isEmpty()) {
        u = frame->GetURL();
      } else {
        u.FromString(url.toStdString());
      }
      frame->ExecuteJavaScript(c, u, 0);

      return true;
    }
  }

  return false;
}

**Comment by tishion** [comment]
你帮忙提个PR？

**Comment by tishion** [comment]
https://github.com/CefView/QCefView/commit/0147afe13babc243e0990b2a0db59079a6626460 
Fixed

**Comment by tishion** [comment]
@cipher1985 

Thanks and Fixed https://github.com/CefView/QCefView/commit/2c40eb8af8901e273826d10719839a1419785c0e

**Comment by cipher1985** [comment]
Good job~
----- 原始邮件 -----
发件人：Sheen Tian ***@***.***>
收件人：CefView/QCefView ***@***.***>
抄送人：cipher1985 ***@***.***>,  Mention ***@***.***>
主题：Re: [CefView/QCefView] mCefView->executeJavascript(QCefView::MainFrameID, callbackString, "") Crash (Issue #58)
日期：2024年03月30日 15点57分


@cipher1985
Thanks and Fixed 2c40eb8
