### ISSUE TITLE
Run javascript

### ISSUE THREAD

**Issue by jcf1002-stack** [CefView/QCefView#6]
**Hi. I've found QCefView is very useful.**
But I've problem.
I'm so beginner that I don't know how to run javascript code and return value from javascript.
When i using QWebEngineView class , following code runs well.

**QWebEngineView mainWebView;
QWebEnginePage page = mainWebView.page();
page.runJavaScript("document.title", [](const QVariant &v) { qDebug() << v.toString(); });**

_Can i implement above action using QCefView instead of QWebEngineView?_

Best regards.

**Comment by tishion** [comment]
CEF did not provide similar approach to execute JavaScript, but i believe you can achive your requirement with the [Interoperability](https://cefview.github.io/QCefView/docs/guide/Interoperability) provided by QCefView.
