### ISSUE TITLE
QCefViewTest.exe无法正常退出

### ISSUE THREAD

**Issue by metaroad** [CefView/QCefView#62]
编译QCefViewTest.exe，运行，然后关闭QCefViewTest.exe，看到：系统任务管理器里面仍然有一个QCefViewTest进程。

环境：
Qt版本： Qt\5.15.2\msvc2019_64
Cef：cef_binary_98.1.21+g9782362+chromium-98.0.4758.102_windows64.tar.bz2
vs2019
cmake 3.22.0

QCefView和QCefViewCore都是今天拉的最新版

**Comment by tishion** [comment]
你换了最新版本的CEF的话，先自己解决一下，每个CEF版本都有改动，我没有办法去适配所有不同版本的CEF。

**Comment by metaroad** [comment]
用的就是最新版本呀。今天上午才拉的

**Comment by metaroad** [comment]
你推荐用什么CEF版本呢？

**Comment by metaroad** [comment]
![image](https://user-images.githubusercontent.com/76619644/157623090-cb9896b4-49f0-448a-9571-1f5bf02c55d6.png)

CEF换了95.7.12+g99c4ac0+chromium-95.0.4638.54，也是一样的效果

**Comment by androrz** [comment]
> ![image](https://user-images.githubusercontent.com/76619644/157623090-cb9896b4-49f0-448a-9571-1f5bf02c55d6.png)
> 
> CEF换了95.7.12+g99c4ac0+chromium-95.0.4638.54，也是一样的效果

你好, 找到原因了吗

**Comment by tishion** [comment]
#63 duplicated

**Comment by tishion** [comment]
Fixed:
Commit: https://github.com/CefView/QCefView/commit/7c93bbb444138bbf54ca299f4198baafe9ebc6a4
