### ISSUE TITLE
换成CEF 95.7.12+g99c4ac0+chromium-95.0.4638.54版本后QCefViewTest仍然无法正常退出

### ISSUE THREAD

**Issue by metaroad** [CefView/QCefView#63]
环境：
Qt版本： Qt\5.15.2\msvc2019_64
Cef：95.7.12+g99c4ac0+chromium-95.0.4638.54
vs2019
cmake 3.22.0

QCefView和QCefViewCore都是今天拉的最新版

**Comment by metaroad** [comment]
![image](https://user-images.githubusercontent.com/76619644/157779521-27c00d41-a772-464c-8d3c-5be07e42c4a8.png)

**Comment by metaroad** [comment]
你用的qt什么版本呢？

**Comment by tishion** [comment]
6.2.2无法复现

5.15.2这个比较早了，早期的时候这个版本没问题，但是QCefView更新了很多，有可能不兼容了，你换新版本Qt试试？

**Comment by metaroad** [comment]
qt换成了6.2.3，没有这个问题了。

**Comment by tishion** [comment]
那看来确实是老版本问题了，但是现在老版本不让我下载了。

**Comment by metaroad** [comment]
可以下载呀。QT老版本可以下的。打开QT根目录下的MaintenanceTool.exe，就可以装呀
![image](https://user-images.githubusercontent.com/76619644/157798826-6c4604b9-d472-434f-9948-c36b235a5fc3.png)

**Comment by tishion** [comment]
Fixed:
Commit: https://github.com/CefView/QCefView/commit/7c93bbb444138bbf54ca299f4198baafe9ebc6a4
