### ISSUE TITLE
windows下无法正常退出应用

### ISSUE THREAD

**Issue by androrz** [CefView/QCefView#64]
Qt版本是5.15.2_msvc2019, 
Cef的版本是cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows32
集成之后,  调用qApp->quit()无法退出应用, 发现进程管理器里面应用还在.

**Comment by tishion** [comment]
The thread 0x7224 has exited with code 0 (0x0).
Exception thrown at 0x00007FFEF2394F69 (KernelBase.dll) in QCefViewTest.exe: 0x0000071A: The remote procedure call was canceled, or if a call time-out was specified, the call timed out.
[DEBUG]CefViewBrowserApp::~CefViewBrowserApp
The thread 0x2b28 has exited with code 0 (0x0).
The thread 0x7260 has exited with code 0 (0x0).
The thread 0x6e70 has exited with code 0 (0x0).
The thread 0x6c90 has exited with code 0 (0x0).
The thread 0x524c has exited with code 0 (0x0).
The thread 0x76f0 has exited with code 0 (0x0).
The thread 0x7194 has exited with code 0 (0x0).
The thread 0x73b4 has exited with code 0 (0x0).
The thread 0x63ec has exited with code 0 (0x0).
The thread 0x75a4 has exited with code 0 (0x0).
The thread 0x7740 has exited with code 0 (0x0).
The thread 0x76e4 has exited with code 0 (0x0).
The thread 0xb58 has exited with code 0 (0x0).
The thread 0x421c has exited with code 0 (0x0).
The thread 0x6ffc has exited with code 0 (0x0).
The thread 0x2458 has exited with code 0 (0x0).
The thread 0x73c0 has exited with code 0 (0x0).
The thread 0x6c74 has exited with code 0 (0x0).
The thread 0x7514 has exited with code 0 (0x0).
The thread 0x32b0 has exited with code 0 (0x0).
The thread 0x53d4 has exited with code 0 (0x0).
The thread 0x62c8 has exited with code 0 (0x0).
The program '[23420] QCefViewTest.exe' has exited with code 0 (0x0).

无法复现。
Qt版本：5.15.2-vcpkg自行编译版本
Cef的版本：cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows32

Qt兼容性的问题不再跟进，建议更换Qt版本。

**Comment by tishion** [comment]
Fixed:
Commit: https://github.com/CefView/QCefView/commit/7c93bbb444138bbf54ca299f4198baafe9ebc6a4
