### ISSUE TITLE
QCefView对QT最低版本有要求吗

### ISSUE THREAD

**Issue by zhenjing** [CefView/QCefView#67]
想用Qt5.13.2，CEF89, 用VS2017来编译，不知道是否支持？
Qt5.13.2，CEF89支持用VS2017编译。

**Comment by tishion** [comment]
Qt 5 和 6 理论上都支持，但是目前有部分反馈说5.15.2版本无法正常退出。
参见：
#62
#64

**Comment by zhenjing** [comment]
Qt5.13.2，cef_binary_89.0.18+gb36241d+chromium-89.0.4389.114_windows64，最新QCefView，用VS2017编译 x64 编译通过。QCefView自带example运行正常。
没仔细测试，还未在项目使用。
