### ISSUE TITLE
老大，请教一个问题，为什么要开启单渲染模式？

### ISSUE THREAD

**Issue by w08** [CefView/QCefView#69]
为啥开启单渲染进程模式呢？

**Comment by tishion** [comment]
最初没有做跨平台支持的时候是多线程的，但是多线程模式只有windows和macOS支持，后期改造为了支持跨平台，统一底层实现所以全部改用单线程了。现在如果要改造成多线程就要考虑线程的marshalling，改动成本稍微大点，所以也没有进行。

另外你还想问为啥不支持OSR渲染模式，其实也是做了尝试，但是单线程模式下OSR性能很差，所以就搁浅了。

**Comment by w08** [comment]
开启了，貌似没什么错误和影响  ，在windows下

**Comment by tishion** [comment]
> 开启了，貌似没什么错误和影响 ，在windows下

开启多线程之后QCefView的那些signal和回调的调用线程就变成了CEF的main browser线程，这个需要注意，signal还好，但是回调函数，比如OnBeforPopup这些，如果你需要重载并且在重载函数里访问Qt的UI资源就要用MetaObject投递到Qt主线程去做。

**Comment by tishion** [comment]
你用命令行是没法开启的，现在的代码不支持，无法运行。

**Comment by xiaobingcaicai** [comment]
单渲染模式是在哪开启的？最新版的支持多线程了？

**Comment by tishion** [comment]
https://github.com/CefView/QCefView/blob/496033379e17054e2e6ae440fc07a7c7ba23c8a2/src/win/details/QCefContextPrivate_win.cpp#L17

看这里，不过这个设置需要整体架构配合，中间改了几版，不知道现在还能不能直接改成单线程模式

**Comment by tishion** [comment]
这个问题说的不是渲染多线程，而是cef的消息循环工作模式
