### ISSUE TITLE
最小化后，visibilitychange的事件丢失，不知道什么引起的。其他浏览器可以，默认的cef DEMO也是可以。

### ISSUE THREAD

**Issue by w08** [CefView/QCefView#70]
用如下代码新建保存为1.html，然后浏览器打开，或者用CEF原生DEMO打开 都可以看到最小化的变化。 QCEF不行。。。

`
<script>
  document.body.insertAdjacentHTML('afterbegin', '<p>' + navigator.userAgent + '</p>')
  setInterval(function() {
    document.body.insertAdjacentHTML('afterbegin', '<p>' + Date.now() + document.visibilityState + '</p>')
  }, 1000)
  document.addEventListener("visibilitychange", function() {
    console.log('---visibilitychange', document.visibilityState );
  })
</script>
`

**Comment by w08** [comment]
<!DOCTYPE html>
<html>
<body>
  <h3>测试PC黑屏问题</h3>
  <div style="font-size: 36px;">Time:<span id="tt"></span></div>
</body>
<script>
  document.body.insertAdjacentHTML('afterbegin', '<p>' + navigator.userAgent + '</p>')
  setInterval(function() {
    document.body.insertAdjacentHTML('afterbegin', '<p>' + Date.now() + document.visibilityState + '</p>')
  }, 1000)
  document.addEventListener("visibilitychange", function() {
    console.log('---visibilitychange', document.visibilityState );
  })
</script>
</html>

**Comment by tishion** [comment]
Commit:https://github.com/CefView/QCefView/commit/b607436182b1375fe6757652ef99915ce71b3808
