### ISSUE TITLE
缺少manifest文件，QCefView触屏无法唤起输入键盘

### ISSUE THREAD

**Issue by zhenjing** [CefView/QCefView#73]
环境：win10+触摸
程序：QCefViewTest
问题：在网页点击输入文本框，无法唤起输入键盘
解决方式：添加 QCefViewTest.manifest 后，键盘输入正常

程序的清单生成为什么会影响键盘唤起呢？

**Comment by zhenjing** [comment]
@tishion 查了manifest 用途，用于解决程序兼容性问题：https://docs.microsoft.com/zh-cn/windows/win32/sysinfo/targeting-your-application-at-windows-8-1?redirectedfrom=MSDN。是这个目的吗？还是其他原因？
CEF有关于window兼容性问题的说明吗？

**Comment by tishion** [comment]
这不属于CEF的问题，而应该是集成CEF的应用开发者自行解决，QCefView也不关注这个问题，因为manifest是给最终应用程序使用的，与库无关。

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
