### ISSUE TITLE
error C2664: “CefViewBrowserClient::CefViewBrowserClient(const CefViewBrowserClient &)”: 无法将参数 1 从“std::shared_ptr<CCefClientDelegate>”转换为“const CefViewBrowserClient &”

### ISSUE THREAD

**Issue by reghtml** [CefView/QCefView#75]
QT版本 5.7.1  系统版本win10  

下载最新版的 QCefView  和  最新版 CefViewCore ，编译有一处错误

 error C2664: “CefViewBrowserClient::CefViewBrowserClient(const CefViewBrowserClient &)”: 无法将参数 1 从“std::shared_ptr<CCefClientDelegate>”转换为“const CefViewBrowserClient &”

![图片](https://user-images.githubusercontent.com/15364651/161408028-8d0d6e0c-02d0-41a6-bfdb-a3b98670d4d0.png)

CefViewBrowserClient 这个类的构造函数只有一个2参数的，没有找到1参数的
![图片](https://user-images.githubusercontent.com/15364651/161408184-1636b2c7-50ab-46fa-bf96-e3a7ce6833ad.png)

麻烦 您看下还是什么问题呢 ♪(･ω･)ﾉ

**Comment by tishion** [comment]
QCefView项目是通过submodule方式依赖CefViewCore项目的，每一个QCefView的commmit都对应一个CefViewCore的commit，不能都使用最新的，而应该使用匹配的。

正确操作是先选择你要使用的QCefView的版本，然后通过submodule方式更新到其对应的Core版本。

**Comment by tishion** [comment]
你拉了最新版本的core，但是qcefview现在不是依赖最新版的core，所以你应该discard core的change

**Comment by Hua-King** [comment]
> 你拉了最新版本的core，但是qcefview现在不是依赖最新版的core，所以你应该discard core的change

不明白，那QCefView和QCefViewCore怎么匹配上相互正确的版本号呢？通过commit的sha1吗？找出两者的一致性？

**Comment by tishion** [comment]
建议搜索一下git submodule相关知识
