### ISSUE TITLE
js调用C++

### ISSUE THREAD

**Issue by Hua-King** [CefView/QCefView#78]
发现js调C++方式不够灵活。
![image](https://user-images.githubusercontent.com/103172877/163350636-9e0c270e-956a-47e1-b0a0-4b12713bd007.png)
直接这样写貌似不行。
必须要传入第二个参数，哪怕是空的都行。
![image](https://user-images.githubusercontent.com/103172877/163350929-166279b0-ce1c-4ba4-b136-4477bb7a3a3f.png)
是否可以调整？

**Comment by tishion** [comment]
https://github.com/CefView/CefViewCore/blob/4c5f6da8e8a6e2c3e0e313df0fef217b303b7ff9/src/CefView/CefBrowserApp/CefViewBrowserClient.cpp#L121-L130

```cpp
bool
CefViewBrowserClient::InvokeMethod(CefRefPtr<CefBrowser> browser,
                                   CefRefPtr<CefFrame> frame,
                                   CefRefPtr<CefProcessMessage> message)
{
  // validate the argument list
  CefRefPtr<CefListValue> arguments = message->GetArgumentList();
  if (!arguments || (arguments->GetSize() < 2))  // 这一行改为 if (!arguments || (arguments->GetSize() < 1))
    return false;
```

main分支目前依赖了一个较旧的core，所以目前无法切换，你先自己修改你本地的core就行了。

**Comment by Hua-King** [comment]
> 

哪一个分支比较新？修改了这个问题的呢？

**Comment by tishion** [comment]
都没有修改

**Comment by tishion** [comment]
Fixed
https://github.com/CefView/QCefView/pull/80
