### ISSUE TITLE
默认右键菜单问题

### ISSUE THREAD

**Issue by Hua-King** [CefView/QCefView#79]
我用官网CEF Demo测试发现可以默认有右键
![image](https://user-images.githubusercontent.com/103172877/163530464-f888e31f-1ed0-444a-ab52-4fbe87beb47c.png)
为啥咱们QCefView没有右键呢？是屏蔽了吗？怎么开启呢？

**Comment by tishion** [comment]
Fixed
https://github.com/CefView/QCefView/pull/80
