### ISSUE TITLE
用最新的代码运行example崩溃

### ISSUE THREAD

**Issue by hijkstrz** [CefView/QCefView#81]
**Describe the bug**
用最新的代码运行example崩溃

**To Reproduce**
拉取最新的代码运行example, QCefView: main, QCefViewCore:  commit 8db29e71206507096b2bda6074f70a5e402d8d6f

**Expected behavior**
example正常运行

**Screenshots**
![avatar](https://s3.bmp.ovh/imgs/2022/04/18/ff0e67e0c9180c51.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Additional context**
无

**Comment by tishion** [comment]
Fixed 
https://github.com/CefView/QCefView/commit/1e52738f9a7c392a453f5f9dd76f393a27f46979
