### ISSUE TITLE
cefQueryRequest信号无法收到

### ISSUE THREAD

**Issue by hijkstrz** [CefView/QCefView#84]
**Describe the bug**
使用自带的示例, index.html里js调用native方法, cefQueryRequest信号无法被处理
**To Reproduce**
拉取最新的代码运行example, QCefView: main, QCefViewCore: commit 38e02107868505ede52a52d3b7e2bea57eac40e4, 以win32运行自带的webres/index.html, 运行 Test Case for QCefQuery, 点击Query, native方法onQCefQueryRequest没被处理.

**Expected behavior**
native方法onQCefQueryRequest被处理

**Screenshots**
![](https://s3.bmp.ovh/imgs/2022/04/23/5303e20445afa748.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Qt: 5.15.2

**Comment by tishion** [comment]
Fixed
https://github.com/CefView/QCefView/commit/b1a7637b5b5141dfb38646f8caae11144d6ce048
