### ISSUE TITLE
用最新的代码无法编译通过

### ISSUE THREAD

**Issue by hijkstrz** [CefView/QCefView#85]
**Describe the bug**
拉取解决了[此bug](https://github.com/CefView/QCefView/issues/84)之后的最新代码, 无法编译通过, 缺少文件.

**To Reproduce**
拉取最新的代码运行example, QCefView: main, QCefViewCore: commit 38e02107868505ede52a52d3b7e2bea57eac40e4

**Expected behavior**
能正常编译运行

**Screenshots**
![](https://s3.bmp.ovh/imgs/2022/04/24/fd1c863d6b4b3841.png)

**Desktop (please complete the following information):**
 - OS: Windows
 
**Additional context**
无

**Comment by tishion** [comment]
删除build目录重新cmake生成

**Comment by hijkstrz** [comment]
> 删除build目录重新cmake生成

验证OK
