### ISSUE TITLE
QT4 能支持下不？ 

### ISSUE THREAD

**Issue by cgisky** [CefView/QCefView#86]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tishion** [comment]
不能

**Comment by ljg2414966411** [comment]
@tishion 大佬，您好，基于Qt4.8.6 & CEF87 ，使用cef原生窗口模式遇到了无法解决的输入法切换问题，经过我的测试QCefView-OSR是可以支持中文输入法切换的 ，想咨询下，将QCefView改造为支持Qt4.8.x是否有可行性？
