### ISSUE TITLE
is:open label:Linux：linux编译问题

### ISSUE THREAD

**Issue by xiaozengbing** [CefView/QCefView#88]
您好，我在uos上编译您的项目，程序能启动，但是网页却一直显示不了，是因为在linux上这个项目还没完成的原因吗？

**Comment by tishion** [comment]
Linux的话你用OSR模式吧，子窗口模式不能正常工作。

**Comment by xiaozengbing** [comment]
> 
好的，我试试，谢谢

**Comment by xiaozengbing** [comment]
> Linux的话你用OSR模式吧，子窗口模式不能正常工作。

使用osr模式编译网页显示成功了，谢谢 @
