### ISSUE TITLE
Linux平台QCefView.so库的使用问题

### ISSUE THREAD

**Issue by xiaozengbing** [CefView/QCefView#89]
您好，我在Linux上编译成功，使用您用cmake构建的测试用例QCefViewTest也是成功的；
于是我想建一个qt项目（参照你的用例）来测试QCefView.so这个库，但是在initialize QCefContext的时候，调试进入QCefContextPrivate::initializeCef这个接口中的  if (!CefInitialize(main_args, cef_settings, app, nullptr)) 这个语句就出不来了，
请问您知道是什么问题吗？是pro文件里需要添加什么配置吗？

**Comment by xiaozengbing** [comment]
![image](https://user-images.githubusercontent.com/59190956/166704009-662ec4a7-b8a6-4e8b-be2d-683af37ba2cf.png)
是要在qmake中设置libcef.so 与 libc.so库的加载顺序吗？

**Comment by tishion** [comment]
> 

是的，debug模式下需要保证libcef优先于c运行时库加载，release模式下不需要。

**Comment by xiaozengbing** [comment]
在qmake中先链接libcef再去链接libQCefView就成功了，但是我有个疑问，libcef不是libQCefView的依赖库吗，为什么要在测试用例里去链接libcef呢，我看windows都是只需要链接libQCefView就行了

**Comment by tishion** [comment]
> 在qmake中先链接libcef再去链接libQCefView就成功了，但是我有个疑问，libcef不是libQCefView的依赖库吗，为什么要在测试用例里去链接libcef呢，我看windows都是只需要链接libQCefView就行了

你说的没错，但是因为debug模式下libcef有这个限制，需要在libc之前加载，所以这里并不是为了依赖libcef，而是为了调整加载顺序所以才显式的声明一下。

**Comment by tishion** [comment]
https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=15118&start=10

**Comment by xiaozengbing** [comment]
> 哦哦哦，感谢解答~
