### ISSUE TITLE
Mac OSX 编译

### ISSUE THREAD

**Issue by vinsonlin** [CefView/QCefView#9]
@tishion HI，能提供一下Mac OSX平台下的使用教程吗？XCode编译好QCefView.framework，QT项目编译正常通过，运行崩溃。

**Comment by KingfisherTao** [comment]
个人猜测，你是不是要把生成的 bin(debug / release) 目录下的文件放到你的Qt 项目下的 debug/release 目录中？

**Comment by tishion** [comment]
@vinsonlin QCefView目前还不支持macOS。

**Comment by zfhenull** [comment]
你是怎么在mac上编译通过的？用的什么工具能告诉我吗

**Comment by zfhenull** [comment]
我的微信1012493740 麻烦教一下

**Comment by tishion** [comment]
目前还QCefView还不支持mac,可以考虑cocoacefvie

**Comment by xmcy0011** [comment]
请问是因为什么原因呢？CocoaCefView不就变成原生的了吗？QT+CEF不能在macos下运行吗？

**Comment by zfhenull** [comment]
我已经放弃了，QCefView还有一个问题：触屏的电脑上，调用触屏的软键盘有问题，软键盘无法输入到内嵌的web里。

**Comment by tishion** [comment]
#25 Support Liunx and macOS

**Comment by liyang0327** [comment]
在M1上，可以正常生成arm的xcode的工程文件，但是用版本号：Version 13.3.1 (13E500a)的xcode提示工程文件损坏，这个有解决方案嘛？提示这个错误：The project ‘QCefView’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
