### ISSUE TITLE
error on compile on Windows10

### ISSUE THREAD

**Issue by lanmanck** [CefView/QCefView#91]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

`
libcef_dll_wrapper.cc
  libcef_dll_wrapper2.cc
G:\svn_workcopy\QCefView\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64\include/base/inter
nal/cef_bind_internal.h(1250): error C2440: 'initializing': cannot convert from 'R (__cdecl *)(base::internal::BindStat
eBase *,conditional<_Test,const std::string&,const std::string&>::type)' to 'PolymorphicInvoke' [G:\svn_workcopy\QCefVi
ew\.build\Windows\CefViewCore\libcef_dll_wrapper\libcef_dll_wrapper.vcxproj]
          with
          [
              R=std::basic_string<char,std::char_traits<char>,std::allocator<char>>
          ] (compiling source file G:\svn_workcopy\QCefView\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4
  638.54_windows64\libcef_dll\wrapper\cef_resource_manager.cc)
  G:\svn_workcopy\QCefView\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64\include/base/int
  ernal/cef_bind_internal.h(1250): note: This conversion requires a reinterpret_cast, a C-style cast or function-style
  cast (compiling source file G:\svn_workcopy\QCefView\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.5
  4_windows64\libcef_dll\wrapper\cef_resource_manager.cc)
  G:\svn_workcopy\QCefView\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64\include/base/cef
  _bind.h(123): note: see reference to function template instantiation 'decltype(auto) base::internal::BindImpl<base::R
  epeatingCallback,std::string(__cdecl &)(const std::string &),>(Functor)' being compiled
          with
          [
              Functor=std::string (__cdecl &)(const std::string &)
          ] (compiling source file G:\svn_workcopy\QCefView\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4
  638.54_windows64\libcef_dll\wrapper\cef_resource_manager.cc)
  G:\svn_workcopy\QCefView\CefViewCore\dep\cef_binary_95.7.12+g99c4ac0+chromium-95.0.4638.54_windows64\libcef_dll\wrapp
  er\cef_resource_manager.cc(424): note: see reference to function template instantiation 'base::RepeatingCallback<std:
  :string (const std::string &)> base::BindRepeating<std::string(__cdecl &)(const std::string &),>(Functor)' being comp
  iled
          with
          [
              Functor=std::string (__cdecl &)(const std::string &)
          ]

G:\svn_workcopy\QCefView>

`

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/macOS/Linux]

**Additional context**

**Comment by tishion** [comment]
应该是你自己的环境问题。
