### ISSUE TITLE
QCefViewPrivate.cpp 的 179 行的BUG。

### ISSUE THREAD

**Issue by leashi** [CefView/QCefView#93]
QCefViewPrivate.cpp 的 179 行
connect(q_ptr->windowHandle(), SIGNAL(screenChanged(QScreen*)), this, SLOT(onViewScreenChanged(QScreen*)));
修改为：
connect(q_ptr->window()->windowHandle(), SIGNAL(screenChanged(QScreen*)), this, SLOT(onViewScreenChanged(QScreen*)));

QCefView 作为子窗口时，q_ptr->windowHandle()为空。

**Comment by tishion** [comment]
你以后发现问题可以直接帮忙提个PR么？

**Comment by tishion** [comment]
https://github.com/CefView/QCefView/commit/65ce6222e82f6ca70661336fd529e46237c65964
Fixed
