### ISSUE TITLE
linux版本库的使用问题

### ISSUE THREAD

**Issue by xiaozengbing** [CefView/QCefView#94]
我编译出来的库在我本地使用正常，但是在其他人电脑上使用时报错 ：
LaunchProcess: failed to execvp:CefViewWing；
所有库与测试程序都放在同一目录下了；
请问您知道是什么问题吗？
![bbde8ad9cad1cb8c654b9b03f5196f8](https://user-images.githubusercontent.com/59190956/168746864-ee0dd2ec-663c-43fb-b9d1-bf864a307a58.png)

**Comment by xiaozengbing** [comment]
使用debug调试时发现崩溃在initialize QCefContext 中

**Comment by xiaozengbing** [comment]
![image](https://user-images.githubusercontent.com/59190956/168749376-85b941cf-c4d1-441e-b87d-a72a0c0686f6.png)

**Comment by tishion** [comment]
有可能是权限问题。

**Comment by lanmanck** [comment]
> 有可能是权限问题。

哥你还会中文，大赞

**Comment by tishion** [comment]
linux需要你自己考虑如何打包，其中涉及到loader的search path等问题，请自行解决。

**Comment by xiaozengbing** [comment]
好的，谢谢





------------------ 原始邮件 ------------------
发件人: Sheen Tian ***@***.***&gt;
发送时间: 2022年6月6日 14:27
收件人: CefView/QCefView ***@***.***&gt;
抄送: xiaozengbing ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [CefView/QCefView] linux版本库的使用问题 (Issue #94)





 
linux需要你自己考虑如何打包，其中涉及到loader的search path等问题，请自行解决。
