### ISSUE TITLE
OSR mode要求QT最低版本是多少？

### ISSUE THREAD

**Issue by zhenjing** [CefView/QCefView#95]
QT 5.13.2 编译OSR，QT缺少一些接口。
win/linux/mac 哪些QT版本有编译测试过？

**Comment by tishion** [comment]
OSR开发过程中都是基于6.0版本的，5.0版本的Qt没有试过，具体哪些接口缺少你发出来看看。

**Comment by zhenjing** [comment]
这2个：
CCefClientDelegate_RenderHandler.cpp(20): error C2039: “screen”: 不是“QWidget”的成员 
QCefViewPrivate.cpp(670): error C2039: “position”: 不是“QWheelEvent”的成员

**Comment by tishion** [comment]
Fixed https://github.com/CefView/QCefView/commit/03740ee86f2e76f5b52f9bbc1118b9f1b8975a81
